version: '3.5'

networks:
  yafin:
    driver: bridge


services:

  postgres:
    image: postgres:12.7
    volumes:
    # we need to manage simple logic of our app before
    # making data volume, which will save all info if
    # docker image will be stopped
      - ../sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=yahoofinance
    ports:
      - 5431:5432
    networks:
      - yafin

