version: '3.5'

networks:
  yafin:
    driver: bridge


services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "yafin-zookeeper"
    networks:
      - "yafin"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # See:
  # https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:2.5.0
    container_name: "yafin-kafka"
    networks:
      - "yafin"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  postgres:
    image: postgres:12.7
    volumes:
    # we need to manage simple logic of our app before
    # making data volume, which will save all info if
    # docker image will be stopped
      - ../sql/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=yahoofinance
    ports:
      - 5431:5432
    networks:
      - yafin

