CREATE TABLE ticker_dictionary (
    id integer PRIMARY KEY,
    name text,
    tcs_ticker text,
    yahoo_ticker text);

INSERT INTO ticker_dictionary VALUES
(1, 'InterDigItal Inc' ,'IDCC', 'IDCC'),
(2, 'RH' ,'RH', 'RH'),
(3, 'Seagen Inc.' ,'SGEN', 'SGEN'),
(4, 'Navient' ,'NAVI', 'NAVI'),
(5, 'Winnebago Industries Inc' ,'WGO', 'WGO'),
(6, 'ГК Мать и дитя' ,'MDMG', 'MDMG.IL'),
(7, 'Twist Bioscience' ,'TWST', 'TWST'),
(8, 'Robert Half' ,'RHI', 'RHI'),
(9, 'Univar Solutions Inc' ,'UNVR', 'UNVR'),
(10, 'Fix Price Group' ,'FIXP', 'FIXP.IL'),
(11, 'Ubiquiti Inc' ,'UI', 'UI'),
(12, 'Cerner' ,'CERN', 'CERN'),
(13, 'Shoals Technologies Group, Inc.' ,'SHLS', 'SHLS'),
(14, 'Terminix Global Holdings' ,'TMX', 'TMX'),
(15, '3D Systems Corp' ,'DDD', 'DDD'),
(16, 'Kennametal Inc' ,'KMT', 'KMT'),
(17, 'ONEOK' ,'OKE', 'OKE'),
(18, 'McDonald’s' ,'MCD', 'MCD'),
(19, 'Barrett Business Services Inc' ,'BBSI', 'BBSI'),
(20, 'Discovery Communications (C)' ,'DISCK', 'DISCK'),
(21, 'MGP Ingredients' ,'MGPI', 'MGPI'),
(22, 'JD.com' ,'JD', 'JD'),
(23, 'Quidel Corp' ,'QDEL', 'QDEL'),
(24, 'TCR2 Therapeutics Inc' ,'TCRR', 'TCRR'),
(25, 'Select Energy Services Inc' ,'WTTR', 'WTTR'),
(26, 'China Southern Airlines' ,'ZNH', 'ZNH.F'),
(27, 'Allegiant Travel Co' ,'ALGT', 'ALGT'),
(28, 'Ingersoll-Rand' ,'IR', 'IR'),
(29, 'Whirlpool' ,'WHR', 'WHR'),
(30, 'Total System Services' ,'TSS', '-'),
(31, 'Advanced Drainage Systems' ,'WMS', 'WMS'),
(32, 'Wyndham Hotels & Resorts' ,'WH', 'WH'),
(33, 'PUMA SE' ,'PUM@DE', 'PUM.DE'),
(34, 'Московская Биржа' ,'MOEX', 'MOEX.ME'),
(35, 'MetLife' ,'MET', 'MET'),
(36, 'Agios Pharmaceuticals Inc' ,'AGIO', 'AGIO'),
(37, 'Omnicell Inc' ,'OMCL', 'OMCL'),
(38, 'Pfizer' ,'PFE', 'PFE'),
(39, 'Encore Wire Corporation' ,'WIRE', 'WIRE'),
(40, 'Seagate' ,'STX', 'STX'),
(41, 'Altair Engineering Inc' ,'ALTR', 'ALTR'),
(42, 'Discover Financial Services' ,'DFS', 'DFS'),
(43, 'Trade Desk Inc/The' ,'TTD', 'TTD'),
(44, 'Hanover Insurance Group' ,'THG', 'THG'),
(45, 'Travelers Cos' ,'TRV', 'TRV'),
(46, 'Fair Isaac Corp' ,'FICO', 'FICO'),
(47, 'The Cooper Companies' ,'COO', 'COO'),
(48, 'ePlus Inc' ,'PLUS', 'PLUS'),
(49, 'Diamondback Energy Inc' ,'FANG', 'FANG'),
(50, 'CME GROUP' ,'CME', 'CME'),
(51, 'C.H. Robinson Worldwide' ,'CHRW', 'CHRW'),
(52, 'Crocs Inc' ,'CROX', 'CROX'),
(53, 'Targa Resources' ,'TRGP', 'TRGP'),
(54, 'iRobot Corp' ,'IRBT', 'IRBT'),
(55, 'МРСК Урала' ,'MRKU', 'MRKU.ME'),
(56, 'Bluebird Bio Inc' ,'BLUE', 'BLUE'),
(57, 'Alarm com Holdings Inc' ,'ALRM', 'ALRM'),
(58, 'Merck' ,'MRK', 'MRK'),
(59, 'Consolidated Edison' ,'ED', 'ED'),
(60, 'Masco' ,'MAS', 'MAS'),
(61, 'Keurig Dr Pepper' ,'KDP', 'KDP'),
(62, 'Westamerica Bancorporation' ,'WABC', 'WABC'),
(63, 'ServiceNow Inc' ,'NOW', 'NOW'),
(64, 'Brady' ,'BRC', 'BRC'),
(65, 'Western Alliance Bancorp' ,'WAL', 'WAL'),
(66, 'Coinbase' ,'COIN', 'COIN'),
(67, 'Wintrust Financial' ,'WTFC', 'WTFC'),
(68, 'GoDaddy Inc' ,'GDDY', 'GDDY'),
(69, 'Coursera, Inc.' ,'COUR', 'COUR'),
(70, 'LIthia Motors Inc' ,'LAD', 'LAD'),
(71, 'Россети Северо-Запад' ,'MRKZ', 'MRKZ.ME'),
(72, 'Murphy USA Inc' ,'MUSA', 'MUSA'),
(73, 'Berkshire Hathaway' ,'BRK.B', 'BRK-B'),
(74, 'Apergy Corporation' ,'APY', '-'),
(75, 'ТГК-2' ,'TGKB', 'TGKB.ME'),
(76, 'Paycom Software Inc' ,'PAYC', 'PAYC'),
(77, 'Verizon Communications' ,'VZ', 'VZ'),
(78, 'Ferro Corp' ,'FOE', 'FOE'),
(79, 'Dycom Industries Inc' ,'DY', 'DY'),
(80, 'Everbridge Inc' ,'EVBG', 'EVBG'),
(81, 'Apellis Pharmaceuticals' ,'APLS', 'APLS'),
(82, 'ПАО «КАЗАНЬОРГСИНТЕЗ»' ,'KZOS', 'KZOS.ME'),
(83, 'ANSYS' ,'ANSS', 'ANSS'),
(84, 'Take-Two Interactive Software' ,'TTWO', 'TTWO'),
(85, 'John B Sanfilippo & Son Inc' ,'JBSS', 'JBSS'),
(86, 'Cortexyme Inc' ,'CRTX', 'CRTX'),
(87, 'Vanda Pharmaceuticals Inc' ,'VNDA', 'VNDA'),
(88, 'Wal-Mart Stores' ,'WMT', 'WMT'),
(89, 'MercadoLibre Inc' ,'MELI', 'MELI'),
(90, 'Vornado REIT' ,'VNO', 'VNO'),
(91, 'Change Healthcare Inc' ,'CHNG', 'CHNG'),
(92, 'GATX Corporation' ,'GATX', 'GATX'),
(93, 'JB Hunt' ,'JBHT', 'JBHT'),
(94, 'Astra Space' ,'ASTR', 'ASTR'),
(95, 'E.ON SE' ,'EOAN@DE', 'EOAN.DE'),
(96, 'Intuit' ,'INTU', 'INTU'),
(97, 'American Financial Group' ,'AFG', 'AFG'),
(98, 'CarParts.com' ,'PRTS', 'PRTS'),
(99, 'Aptiv' ,'APTV', 'APTV'),
(100, 'Danimer Scientific' ,'DNMR', 'DNMR'),
(101, 'K12 Inc' ,'LRN_old', 'LRN'),
(102, 'Focus Financial Partners Inc' ,'FOCS', 'FOCS'),
(103, 'Mesa Laboratories Inc' ,'MLAB', 'MLAB'),
(104, 'Harsco Corp' ,'HSC', 'HSC'),
(105, 'Johnson Outdoors Inc' ,'JOUT', 'JOUT'),
(106, 'Gibraltar Industries Inc' ,'ROCK', 'ROCK'),
(107, 'Enanta Pharmaceuticals Inc' ,'ENTA', 'ENTA'),
(108, 'Verint Systems Inc' ,'VRNT', 'VRNT'),
(109, 'Green Dot Corp' ,'GDOT', 'GDOT'),
(110, 'Lowe''s' ,'LOW', 'LOW'),
(111, 'MGIC Investment Corp' ,'MTG', 'MTG'),
(112, 'Intercept Pharmaceuticals Inc' ,'ICPT', 'ICPT'),
(113, 'IDEX Corp' ,'IEX', 'IEX'),
(114, 'Duolingo' ,'DUOL', 'DUOL'),
(115, 'Inspire Medical Systems Inc' ,'INSP', 'INSP'),
(116, 'Tesla Motors' ,'TSLA', 'TSLA'),
(117, 'Hawaiian Electric Industries, Inc.' ,'HE', 'HE'),
(118, 'ON Semiconductor Corp' ,'ON', 'ON'),
(119, 'MicroStrategy Inc' ,'MSTR', 'MSTR'),
(120, 'АДР МТС' ,'MBT', 'MKY.F'),
(121, 'The Clorox Company' ,'CLX', 'CLX'),
(122, 'United States Cellular Corp' ,'USM', 'USM'),
(123, 'Dolby Laboratories Inc' ,'DLB', 'DLB'),
(124, 'Knight-Swift Transportation' ,'KNX', 'KNX'),
(125, 'Nubank' ,'NU', 'NU'),
(126, 'WD-40 Co' ,'WDFC', 'WDFC'),
(127, 'Boston Properties REIT' ,'BXP', 'BXP'),
(128, 'CoStar Group Inc' ,'CSGP', 'CSGP'),
(129, 'New Relic Inc' ,'NEWR', 'NEWR'),
(130, 'Pagerduty Inc' ,'PD', 'PD'),
(131, 'Goosehead Insurance, Inc.' ,'GSHD', 'GSHD'),
(132, 'DISH Network Corp' ,'DISH', 'DISH'),
(133, 'Bloomin Brands, Inc.' ,'BLMN', 'BLMN'),
(134, 'TCS Group (Tinkoff Bank holder)' ,'TCS', 'TCS.IL'),
(135, 'Invesco' ,'IVZ', 'IVZ'),
(136, 'Edwards Lifesciences' ,'EW', 'EW'),
(137, 'Pinnacle Financial Partners In' ,'PNFP', 'PNFP'),
(138, 'New York Times' ,'NYT', 'NYT'),
(139, 'Covetrus Inc' ,'CVET', 'CVET'),
(140, 'Yandex' ,'YNDX', 'YNDX'),
(141, 'Blink Charging Co' ,'BLNK', 'BLNK'),
(142, 'TriNet Group Inc' ,'TNET', 'TNET'),
(143, 'Brixmor Property Group REIT' ,'BRX', 'BRX'),
(144, 'Prestige Consumer Healthcare I' ,'PBH', 'PBH'),
(145, 'Burlington Stores Inc' ,'BURL', 'BURL'),
(146, 'Alliant Energy' ,'LNT', 'LNT'),
(147, 'Simpson Manufacturing Co Inc' ,'SSD', 'SSD'),
(148, 'APA Corporation' ,'APA', 'APA'),
(149, 'Eversource Energy' ,'ES', 'ES'),
(150, 'Chemed Corp' ,'CHE', 'CHE'),
(151, 'Deckers Outdoor Corp' ,'DECK', 'DECK'),
(152, 'Northern Trust' ,'NTRS', 'NTRS'),
(153, 'Ashland Global Holdings Inc' ,'ASH', 'ASH'),
(154, 'Domino''s Pizza Inc' ,'DPZ', 'DPZ'),
(155, 'Monolithic Power Systems' ,'MPWR', 'MPWR'),
(156, 'Банк ВТБ' ,'VTBR', 'VTBR.ME'),
(157, 'Kontoor Brands Inc' ,'KTB', 'KTB'),
(158, 'Cable One' ,'CABO', 'CABO'),
(159, 'BJs Wholesale Club Holdings, Inc.' ,'BJ', 'BJ'),
(160, 'Skechers U.S.A. Inc' ,'SKX', 'SKX'),
(161, 'Zoom Video Communications Inc' ,'ZM', 'ZM'),
(162, 'Barrick Gold' ,'GOLD', 'ABX.TO'),
(163, 'Morningstar' ,'MORN', 'MORN'),
(164, 'Zuora Inc' ,'ZUO', 'ZUO'),
(165, 'Sonoco Products Co' ,'SON', 'SON'),
(166, 'Myriad Genetics Inc' ,'MYGN', 'MYGN'),
(167, 'FTI Consulting Inc' ,'FCN', 'FCN'),
(168, 'Darling Ingredients Inc' ,'DAR', 'DAR'),
(169, 'Greif Inc' ,'GEF', 'GEF'),
(170, 'En+ Group' ,'ENPG', 'ENPG.ME'),
(171, 'Royal Caribbean Cruises' ,'RCL', 'RCL'),
(172, 'TTM Technologies Inc' ,'TTMI', 'TTMI'),
(173, 'Aflac Incorporated' ,'AFL', 'AFL'),
(174, 'Monarch Casino & Resort Inc' ,'MCRI', 'MCRI'),
(175, 'Global-E Online Ltd' ,'GLBE', 'GLBE'),
(176, 'Synchrony Financial' ,'SYF', 'SYF'),
(177, 'First Financial Bankshares, Inc.' ,'FFIN', 'FFIN'),
(178, 'Brinker International Inc' ,'EAT', 'EAT'),
(179, 'TE Connectivity' ,'TEL', 'TEL'),
(180, 'ЧМК' ,'CHMK', 'CHMK.ME'),
(181, 'Organon & Co.' ,'OGN', 'OGN'),
(182, 'ФСК ЕЭС' ,'FEES', 'FEES.ME'),
(183, 'Coterra Energy Inc.' ,'CTRA', 'CTRA'),
(184, 'Nordson Corp' ,'NDSN', 'NDSN'),
(185, 'SK Telecom Co.' ,'SKM', 'SKM'),
(186, 'The Allstate Corporation' ,'ALL', 'ALL'),
(187, 'Cardiovascular Systems Inc' ,'CSII', 'CSII'),
(188, 'SBA Communications REIT' ,'SBAC', 'SBAC'),
(189, 'Praxis Precision Medicines' ,'PRAX', 'PRAX'),
(190, 'Bank of America Corp' ,'BAC', 'BAC'),
(191, 'Ovintiv Inc.' ,'OVV', 'OVV.TO'),
(192, 'Applied Materials' ,'AMAT', 'AMAT'),
(193, 'eHealth Inc' ,'EHTH', 'EHTH'),
(194, 'Walt Disney' ,'DIS', 'DIS'),
(195, 'AnaptysBio Inc' ,'ANAB', 'ANAB'),
(196, 'Банк Возрождение - акции привилегированные' ,'VZRZP', '-'),
(197, 'American Public Education Inc' ,'APEI', 'APEI'),
(198, 'National Western Life Group In' ,'NWLI', 'NWLI'),
(199, 'Apple' ,'AAPL', 'AAPL'),
(200, 'N-able' ,'NABL', 'NABL'),
(201, 'Huntsman' ,'HUN', 'HUN'),
(202, 'Ross Stores' ,'ROST', 'ROST'),
(203, 'GoodRx Holdings Inc' ,'GDRX', 'GDRX'),
(204, 'Acuity Brands' ,'AYI', 'AYI'),
(205, 'BigCommerce Holdings' ,'BIGC', 'BIGC'),
(206, 'Shell АДР' ,'SHEL', 'L3H.F'),
(207, 'Okta Inc' ,'OKTA', 'OKTA'),
(208, 'Jack in the Box' ,'JACK', 'JACK'),
(209, 'Continental AG' ,'CON@DE', 'CON.DE'),
(210, 'Аптечная сеть 36,6' ,'APTK', 'APTK.ME'),
(211, 'Black Knight Inc' ,'BKI', 'BKI'),
(212, 'Citizens Financial Group' ,'CFG', 'CFG'),
(213, 'Booking' ,'BKNG', 'BKNG'),
(214, 'Host Hotels & Resorts REIT' ,'HST', 'HST'),
(215, 'Expedia' ,'EXPE', 'EXPE'),
(216, 'Zendesk Inc' ,'ZEN', 'ZEN'),
(217, 'PTC Inc' ,'PTC', 'PTC'),
(218, 'NextEra Energy' ,'NEE', 'NEE'),
(219, 'Marriott International' ,'MAR', 'MAR'),
(220, 'The Charles Schwab Corporation' ,'SCHW', 'SCHW'),
(221, 'TAL Education Group' ,'TAL', 'IZZ.F'),
(222, 'Occidental Petroleum' ,'OXY', 'OXY'),
(223, 'Medtronic' ,'MDT', 'MDT'),
(224, 'Hostess Brands Inc' ,'TWNK', 'TWNK'),
(225, 'Performance Food Group Co' ,'PFGC', 'PFGC'),
(226, 'Appfolio Inc' ,'APPF', 'APPF'),
(227, 'Netflix' ,'NFLX', 'NFLX'),
(228, 'Truist Financial Corporation' ,'TFC', 'TFC'),
(229, 'Papa John''s International Inc' ,'PZZA', 'PZZA'),
(230, 'Meritage Homes Corp' ,'MTH', 'MTH'),
(231, 'FactSet Research Systems Inc' ,'FDS', 'FDS'),
(232, 'Packaging Corp of America' ,'PKG', 'PKG'),
(233, 'Evolent Health Inc' ,'EVH', 'EVH'),
(234, 'Inovio Pharmaceuticals' ,'INO', 'INO'),
(235, 'Pembina Pipeline Corporation' ,'PBA', 'PPL.TO'),
(236, 'Русгрэйн' ,'RUGR', 'RUGR.ME'),
(237, 'Intel Corporation' ,'INTC', 'INTC'),
(238, 'HeidelbergCement AG' ,'HEI@DE', 'HEI.DE'),
(239, 'Ingevity Corp' ,'NGVT', 'NGVT'),
(240, 'NVR Inc' ,'NVR', 'NVR'),
(241, 'Louisiana-Pacific Corporation' ,'LPX', 'LPX'),
(242, 'Zogenix Inc' ,'ZGNX', 'ZGNX'),
(243, 'Encore Capital Group Inc' ,'ECPG', 'ECPG'),
(244, 'Avery Dennison' ,'AVY', 'AVY'),
(245, 'Marathon Oil' ,'MRO', 'MRO'),
(246, 'Nucor' ,'NUE', 'NUE'),
(247, 'Cargurus Inc' ,'CARG', 'CARG'),
(248, 'NorthWestern Corporation' ,'NWE', 'NWE'),
(249, 'Mosaic' ,'MOS', 'MOS'),
(250, 'Lululemon Athletica Inc' ,'LULU', 'LULU'),
(251, 'Kite Realty Group REIT' ,'KRG', 'KRG'),
(252, 'Vir Biotechnology' ,'VIR', 'VIR'),
(253, 'Workday Inc' ,'WDAY', 'WDAY'),
(254, 'Deutsche Bank AG' ,'DBK@DE', 'DBK.DE'),
(255, 'RBC Bearings Inc' ,'ROLL', 'ROLL'),
(256, 'Planet FItness Inc' ,'PLNT', 'PLNT'),
(257, 'LendingTree Inc' ,'TREE', 'TREE'),
(258, 'Incyte' ,'INCY', 'INCY'),
(259, 'Twenty-First Century Fox (A)' ,'FOXA', 'FOXA'),
(260, 'Shutterstock Inc' ,'SSTK', 'SSTK'),
(261, 'Southwest Gas Holdings' ,'SWX', 'SWX'),
(262, 'DigitalOcean Holdings' ,'DOCN', 'DOCN'),
(263, 'Extra Space Storage REIT' ,'EXR', 'EXR'),
(264, 'Omega Healthcare Investors REIT' ,'OHI', 'OHI'),
(265, 'HeadHunter Group PLC' ,'HHR', 'US42207L1061.SG'),
(266, 'Loyalty Ventures' ,'LYLT', 'LYLT'),
(267, 'Dunkin’ Brands Group' ,'DNKN', '-'),
(268, 'Otis Worldwide' ,'OTIS', 'OTIS'),
(269, 'UGI Corp' ,'UGI', 'UGI'),
(270, 'Revolve Group Inc' ,'RVLV', 'RVLV'),
(271, 'Сегежа' ,'SGZH', 'SGZH.ME'),
(272, 'Sarepta Therapeutics Inc' ,'SRPT', 'SRPT'),
(273, 'Desktop Metal' ,'DM', 'DM'),
(274, 'Avalara Inc' ,'AVLR', 'AVLR'),
(275, 'Service Corp International/US' ,'SCI', 'SCI'),
(276, 'HubSpot Inc' ,'HUBS', 'HUBS'),
(277, 'Kraft Heinz' ,'KHC', 'KHC'),
(278, 'SiTime' ,'SITM', 'SITM'),
(279, 'Clover Health Investments, Corp.' ,'CLOV', 'CLOV'),
(280, 'TripAdvisor' ,'TRIP', 'TRIP'),
(281, 'Trimble Inc' ,'TRMB', 'TRMB'),
(282, 'Adtalem Global Education Inc' ,'ATGE', 'ATGE'),
(283, 'МРСК Волги' ,'MRKV', 'MRKV.ME'),
(284, 'PetIQ Inc' ,'PETQ', 'PETQ'),
(285, 'Mobile Mini Inc' ,'MINI', '-'),
(286, 'General Dynamics' ,'GD', 'GD'),
(287, 'Wheaton Precious Metals' ,'WPM', 'WPM.TO'),
(288, 'Alphabet Class A' ,'GOOGL', 'GOOGL'),
(289, 'American Water Works' ,'AWK', 'AWK'),
(290, 'Nutrien' ,'NTR', 'NTR.TO'),
(291, 'Advance Auto Parts' ,'AAP', 'AAP'),
(292, 'Newell Brands' ,'NWL', 'NWL'),
(293, 'Devon Energy' ,'DVN', 'DVN'),
(294, 'Match Group Inc' ,'MTCH', 'MTCH'),
(295, 'Matterport' ,'MTTR', 'MTTR'),
(296, 'Monday.Com' ,'MNDY', 'MNDY'),
(297, 'News Corp (A)' ,'NWSA', 'NWSA'),
(298, 'Axsome Therapeutics Inc' ,'AXSM', 'AXSM'),
(299, 'BioXcel Therapeutics' ,'BTAI', 'BTAI'),
(300, 'Academy Sports & Outdoors' ,'ASO', 'ASO'),
(301, 'Evercore' ,'EVR', 'EVR'),
(302, 'АЛРОСА' ,'ALRS', 'ALRS.ME'),
(303, 'IAC InterActiveCorp' ,'IAC__old', 'IAC1.MX'),
(304, 'Check Point Software Technologies Ltd' ,'CHKP', 'CHKP'),
(305, 'Inmode Ltd' ,'INMD', 'INMD'),
(306, 'Equitrans Midstream Corporation' ,'ETRN', 'ETRN'),
(307, 'Legacy Housing Corp' ,'LEGH', 'LEGH'),
(308, 'CDK Global' ,'CDK', 'CDK'),
(309, 'UBS Group' ,'UBS', 'UBSG.SW'),
(310, 'Aluminum Corp of China' ,'ACH', 'ACH'),
(311, 'Procter & Gamble' ,'PG', 'PG'),
(312, 'Селигдар' ,'SELG', 'SELG.ME'),
(313, 'Assurant' ,'AIZ', 'AIZ'),
(314, 'Smartsheet Inc' ,'SMAR', 'SMAR'),
(315, 'Addus HomeCare Corp' ,'ADUS', 'ADUS'),
(316, 'Digital Turbine Inc' ,'APPS', 'APPS'),
(317, 'HollyFrontier' ,'HFC', 'HFC'),
(318, 'PGT Innovations Inc' ,'PGTI', 'PGTI'),
(319, 'Dentsply Sirona' ,'XRAY', 'XRAY'),
(320, 'Zurn Water Solutions' ,'ZWS', 'ZWS'),
(321, 'Supernus Pharmaceuticals Inc' ,'SUPN', 'SUPN'),
(322, 'LUKOIL PJSC' ,'LKOD@GS', 'LKOD.IL'),
(323, 'Huaneng Power International' ,'HNP', 'HNP'),
(324, 'Meta Platforms' ,'FB', 'FB'),
(325, 'Western Digital' ,'WDC', 'WDC'),
(326, 'ChampionX Corporation' ,'CHX', 'CHX'),
(327, 'Carrier Global' ,'CARR', 'CARR'),
(328, 'Pure Storage Inc' ,'PSTG', 'PSTG'),
(329, 'Pagseguro Digital Ltd' ,'PAGS', 'PAGS'),
(330, 'MGM Resorts International' ,'MGM', 'MGM'),
(331, 'Telephone & Data Systems Inc' ,'TDS', 'TDS'),
(332, 'Five9 Inc' ,'FIVN', 'FIVN'),
(333, 'SpringWorks Therapeutics' ,'SWTX', 'SWTX'),
(334, 'PPG Industries' ,'PPG', 'PPG'),
(335, 'TEGNA' ,'TGNA', 'TGNA'),
(336, 'Scotts Miracle-Gro Co The' ,'SMG', 'SMG'),
(337, 'Molson Coors Brewing' ,'TAP', 'TAP'),
(338, 'Microchip Technology' ,'MCHP', 'MCHP'),
(339, 'Public Service Enterprise Group' ,'PEG', 'PEG'),
(340, 'Hilton' ,'HLT', 'HLT'),
(341, 'Sleep Number Corp' ,'SNBR', 'SNBR'),
(342, 'Grocery Outlet Holding Corp' ,'GO', 'GO'),
(343, 'EnerSys' ,'ENS', 'ENS'),
(344, 'Stanley Black & Decker' ,'SWK', 'SWK'),
(345, 'Cognizant Technology Solutions' ,'CTSH', 'CTSH'),
(346, 'Booz Allen Hamilton' ,'BAH', 'BAH'),
(347, 'Adaptive Biotechnologies' ,'ADPT', 'ADPT'),
(348, 'Калужская сбытовая компания' ,'KLSB', 'KLSB.ME'),
(349, 'Gap' ,'GPS', 'GPS'),
(350, 'Фармсинтез' ,'LIFE', 'LIFE.ME'),
(351, 'ROBLOX Corp' ,'RBLX', 'RBLX'),
(352, 'Tata Motors' ,'TTM', 'TTM'),
(353, 'ResMed Inc' ,'RMD', 'RMD'),
(354, 'US Physical Therapy Inc' ,'USPH', 'USPH'),
(355, 'Nu Skin Enterprises Inc' ,'NUS', 'NUS'),
(356, 'Delek US Holdings Inc' ,'DK', 'DK'),
(357, 'Ferrari N.V.' ,'RACE', 'RACE'),
(358, 'Tapestry' ,'TPR', 'TPR'),
(359, 'Совкомфлот' ,'FLOT', 'FLOT.ME'),
(360, 'Fulgent Genetics' ,'FLGT', 'FLGT'),
(361, 'Hexcel Corp' ,'HXL', 'HXL'),
(362, 'GMS Inc' ,'GMS', 'GMS'),
(363, 'Городские Инновационные Технологии' ,'GRNT', '-'),
(364, 'Weyerhaeuser REIT' ,'WY', 'WY'),
(365, 'Proto Labs Inc' ,'PRLB', 'PRLB'),
(366, 'GILEAD' ,'GILD', 'GILD'),
(367, 'Энел Россия' ,'ENRU', 'ENRU.ME'),
(368, 'ГТМ' ,'GTRK', 'GTRK.ME'),
(369, 'Anika Therapeutics Inc' ,'ANIK', 'ANIK'),
(370, 'Cleveland-Cliffs' ,'CLF', 'CLF'),
(371, 'QuantumScape Corporation' ,'QS', 'QS'),
(372, 'II-VI Inc' ,'IIVI', 'IIVI'),
(373, 'Pinterest Inc' ,'PINS', 'PINS'),
(374, 'Arrowhead Pharmaceuticals Inc' ,'ARWR', 'ARWR'),
(375, 'Blueprint Medicines Corp' ,'BPMC', 'BPMC'),
(376, 'ЭсЭфАй' ,'SFIN', 'SFIN.ME'),
(377, 'Terreno REIT' ,'TRNO', 'TRNO'),
(378, 'Napco Security Technologies' ,'NSSC', 'NSSC'),
(379, 'Open Lending Corp' ,'LPRO', 'LPRO'),
(380, 'Korea Electric Power' ,'KEP', 'KOP.F'),
(381, 'Janus Henderson Group' ,'JHG', 'JHG'),
(382, '10X Genomics Inc' ,'TXG', 'TXG'),
(383, 'Healthcare Trust of America REIT' ,'HTA', 'HTA'),
(384, 'WEX Inc' ,'WEX', 'WEX'),
(385, 'Rheinmetall AG' ,'RHM@DE', 'RHM.DE'),
(386, 'Магнит' ,'MGNT', 'MGNT.ME'),
(387, 'ГК Самолет' ,'SMLT', 'SMLT.ME'),
(388, '8x8 Inc' ,'EGHT', 'EGHT'),
(389, 'Columbus McKinnon Corp' ,'CMCO', 'CMCO'),
(390, 'Квадра - привилегированные акции' ,'TGKDP', 'TGKDP.ME'),
(391, 'Gentex Corporation' ,'GNTX', 'GNTX'),
(392, 'Jones Lang LaSalle Inc' ,'JLL', 'JLL'),
(393, 'Bank of Hawaii' ,'BOH', 'BOH'),
(394, 'Aerojet Rocketdyne Holdings In' ,'AJRD', 'AJRD'),
(395, 'TransDigm' ,'TDG', 'TDG'),
(396, 'SoFi Technologies' ,'SOFI', 'SOFI'),
(397, 'PubMatic' ,'PUBM', 'PUBM'),
(398, 'Hologic' ,'HOLX', 'HOLX'),
(399, 'Reata Pharmaceuticals Inc' ,'RETA', 'RETA'),
(400, 'Axonics' ,'AXNX', 'AXNX'),
(401, 'ACADIA Pharmaceuticals Inc' ,'ACAD', 'ACAD'),
(402, 'CubeSmart REIT' ,'CUBE', 'CUBE'),
(403, 'The AES Corporation' ,'AES', 'AES'),
(404, 'FMC' ,'FMC', 'FMC'),
(405, 'ManpowerGroup Inc' ,'MAN', 'MAN'),
(406, 'Macy''s' ,'M', 'M'),
(407, 'LabCorp' ,'LH', 'LH'),
(408, 'Wabtec Corp.' ,'WAB', 'WAB'),
(409, 'Baidu' ,'BIDU', 'BIDUN.MX'),
(410, 'Deutsche Post AG' ,'DPW@DE', 'DPW.DE'),
(411, 'Centene Corporation' ,'CNC', 'CNC'),
(412, 'G1 Therapeutics Inc' ,'GTHX', 'GTHX'),
(413, 'LG Display' ,'LPL', 'LPL'),
(414, 'Silvergate Capital Corp.' ,'SI', 'SI'),
(415, 'IDEXX' ,'IDXX', 'IDXX'),
(416, 'FirstCash' ,'FCFS', 'FCFS'),
(417, 'Cogent Communications' ,'CCOI', 'CCOI'),
(418, 'WW International, Inc.' ,'WW', 'WW'),
(419, 'Cameco Corporation' ,'CCJ', 'CCO.TO'),
(420, 'Capri Holdings Limited' ,'CPRI', 'CPRI'),
(421, 'Cara Therapeutics Inc' ,'CARA', 'CARA'),
(422, 'Gazprom PJSC' ,'OGZD@GS', 'GAZ.F'),
(423, 'Roku Inc' ,'ROKU', 'ROKU'),
(424, 'Oracle' ,'ORCL', 'ORCL'),
(425, 'Qurate Retail Inc' ,'QRTEA', 'QRTEA'),
(426, 'Worthington Industries Inc' ,'WOR', 'WOR'),
(427, 'Fiverr International' ,'FVRR', 'FVRR'),
(428, 'VEON' ,'VEON-RX', 'VEON.AS'),
(429, 'FirstEnergy' ,'FE', 'FE'),
(430, 'Syneos Health Inc' ,'SYNH', 'SYNH'),
(431, 'Spirit AeroSystems Holdings' ,'SPR', 'SPR'),
(432, 'Avnet' ,'AVT', 'AVT'),
(433, 'Insulet Corp' ,'PODD', 'PODD'),
(434, 'Лензолото' ,'LNZL', 'LNZL.ME'),
(435, 'BioMarin Pharmaceutical Inc' ,'BMRN', 'BMRN'),
(436, 'ScanSource Inc' ,'SCSC', 'SCSC'),
(437, 'Progressive' ,'PGR', 'PGR'),
(438, 'Xylem' ,'XYL', 'XYL'),
(439, 'Rent-A-Center' ,'RCII', 'RCII'),
(440, 'ChemoCentryx, Inc' ,'CCXI', 'CCXI'),
(441, 'O-I Glass' ,'OI', 'OI'),
(442, 'Agilent Technologies' ,'A', 'A'),
(443, 'Axon Enterprise Inc' ,'AXON', 'AXON'),
(444, 'Rockwell Automation' ,'ROK', 'ROK'),
(445, 'Lightspeed Commerce' ,'LSPD', 'LSPD.TO'),
(446, 'Neurocrine Biosciences Inc' ,'NBIX', 'NBIX'),
(447, 'Bayerische Motoren Werke AG' ,'BMW@DE', 'BMW.DE'),
(448, 'Crane Co' ,'CR', 'CR'),
(449, 'J&J Snack Foods Corp' ,'JJSF', 'JJSF'),
(450, 'McKesson' ,'MCK', 'MCK'),
(451, 'Chefs'' Warehouse Inc' ,'CHEF', 'CHEF'),
(452, 'AMC Networks Inc' ,'AMCX', 'AMCX'),
(453, 'Spirit Realty Capital REIT' ,'SRC', 'SRC'),
(454, 'Pilgrim''s Pride Corp' ,'PPC', 'PPC'),
(455, 'Crown Holdings Inc' ,'CCK', 'CCK'),
(456, 'Kinsale Capital Group' ,'KNSL', 'KNSL'),
(457, 'SiteOne Landscape Supply Inc' ,'SITE', 'SITE'),
(458, 'РБК' ,'RBCM', 'RBCM.ME'),
(459, 'Fresenius Medical Care AG & Co' ,'FME@DE', 'FME.DE'),
(460, 'Affimed NV' ,'AFMD', 'AFMD'),
(461, 'Eagle Pharmaceuticals Inc' ,'EGRX', 'EGRX'),
(462, 'New Jersey Resources Corp' ,'NJR', 'NJR'),
(463, 'Taiwan Semiconductor Manufacturing' ,'TSM', 'TSM'),
(464, 'M/I Homes Inc' ,'MHO', 'MHO'),
(465, 'AAR Corp' ,'AIR', 'AIR'),
(466, 'Россети Центр и Приволжье' ,'MRKP', 'MRKP.ME'),
(467, 'Semtech Corp' ,'SMTC', 'SMTC'),
(468, 'MAXIMUS Inc' ,'MMS', 'MMS'),
(469, 'Deutsche Telekom AG' ,'DTE@DE', 'DTE.DE'),
(470, 'Ford' ,'F', 'F'),
(471, 'КуйбышевАзот - Акции привилегированные' ,'KAZTP', 'KAZTP.ME'),
(472, 'ЛУКОЙЛ' ,'LKOH', 'LKOH.ME'),
(473, 'Corning' ,'GLW', 'GLW'),
(474, 'HealthEquity Inc' ,'HQY', 'HQY'),
(475, 'Invitation Homes REIT' ,'INVH', 'INVH'),
(476, 'Heritage-Crystal Clean Inc' ,'HCCI', 'HCCI'),
(477, 'Piper Sandler Companies' ,'PIPR', 'PIPR'),
(478, 'Полюс Золото' ,'PLZL', 'PLZL.ME'),
(479, 'Deere & Company' ,'DE', 'DE'),
(480, 'Bottomline Technologies DE Inc' ,'EPAY', 'EPAY'),
(481, 'Mid-America Apartment REIT' ,'MAA', 'MAA'),
(482, 'Foot Locker' ,'FL', 'FL'),
(483, 'REX American Resources Corp' ,'REX', 'REX'),
(484, 'Progyny Inc' ,'PGNY', 'PGNY'),
(485, 'Invitae Corp' ,'NVTA', 'NVTA'),
(486, 'Dorman Products Inc' ,'DORM', 'DORM'),
(487, 'Coca-Cola Consolidated Inc' ,'COKE', 'COKE'),
(488, 'MEDNAX Inc' ,'MD', 'MD'),
(489, 'Mondelez' ,'MDLZ', 'MDLZ'),
(490, 'Blackline Inc' ,'BL', 'BL'),
(491, 'AMETEK' ,'AME', 'AME'),
(492, 'Банк Санкт-Петербург' ,'BSPB', 'BSPB.ME'),
(493, 'CyrusOne REIT' ,'CONE', 'CONE'),
(494, 'MillerKnoll' ,'MLKN', 'MLKN'),
(495, 'Sally Beauty Holdings Inc' ,'SBH', 'SBH'),
(496, 'Fastly Inc' ,'FSLY', 'FSLY'),
(497, 'L3Harris Technologies Inc' ,'LHX', 'LHX'),
(498, 'IGM Biosciences Inc' ,'IGMS', 'IGMS'),
(499, 'Cardlytics Inc' ,'CDLX', 'CDLX'),
(500, 'Aramark' ,'ARMK', 'ARMK'),
(501, 'Citrix Systems' ,'CTXS', 'CTXS'),
(502, 'Pioneer Natural Resources' ,'PXD', 'PXD'),
(503, 'News Corp' ,'NWS', 'NWS'),
(504, 'Exelon Corporation' ,'EXC', 'EXC'),
(505, 'AbbVie' ,'ABBV', 'ABBV'),
(506, 'Cryoport' ,'CYRX', 'CYRX'),
(507, 'Block' ,'SQ', 'SQ'),
(508, 'Werner Enterprises Inc' ,'WERN', 'WERN'),
(509, 'UUFP Industries, Inc' ,'UFPI', 'UFPI'),
(510, 'Casey''s General Stores Inc' ,'CASY', 'CASY'),
(511, 'Ventas REIT' ,'VTR', 'VTR'),
(512, 'Boston Beer Co Inc The' ,'SAM', 'SAM'),
(513, 'Carlisle Companies Incorporated' ,'CSL', 'CSL'),
(514, 'Flowserve' ,'FLS', 'FLS'),
(515, 'ЮУНК' ,'UNKL', 'UNKL.ME'),
(516, 'Avient Corporation' ,'AVNT', 'AVNT'),
(517, 'Zions Bancorporation' ,'ZION', 'ZION'),
(518, 'Tabula Rasa HealthCare In' ,'TRHC', 'TRHC'),
(519, 'Мультисистема' ,'MSST', '-'),
(520, 'Amgen' ,'AMGN', 'AMGN'),
(521, 'Veoneer Inc' ,'VNE', 'VNE'),
(522, 'A. O. Smith Corporation' ,'AOS', 'AOS'),
(523, 'ServiceMaster Global Holdings' ,'SERV', '-'),
(524, 'Wynn Resorts' ,'WYNN', 'WYNN'),
(525, 'SVB Financial Group' ,'SIVB', 'SIVB'),
(526, 'BorgWarner' ,'BWA', 'BWA'),
(527, 'Amcor' ,'AMCR', 'AMCR'),
(528, 'Electronic Arts' ,'EA', 'EA'),
(529, 'TCS Group' ,'TCSG', '-'),
(530, 'Reinsurance Group of America I' ,'RGA', 'RGA'),
(531, 'Regal Rexnord' ,'RRX', 'RRX'),
(532, 'UnitedHealth' ,'UNH', 'UNH'),
(533, 'DoorDash' ,'DASH', 'DASH'),
(534, 'HB Fuller Co' ,'FUL', 'FUL'),
(535, 'Vertiv Holdings Co' ,'VRT', 'VRT'),
(536, 'Texas Roadhouse Inc' ,'TXRH', 'TXRH'),
(537, 'Chewy Inc' ,'CHWY', 'CHWY'),
(538, 'Willis Towers Watson' ,'WTW', 'WTW'),
(539, 'Pool Corp' ,'POOL', 'POOL'),
(540, 'Unitil Corporation' ,'UTL', 'UTL'),
(541, 'Webster Financial Corporation' ,'WBS', 'WBS'),
(542, 'Lumen Technologies' ,'LUMN', 'LUMN'),
(543, 'M&T Bank' ,'MTB', 'MTB'),
(544, 'PPL' ,'PPL', 'PPL'),
(545, 'МГТС - акции привилегированные' ,'MGTSP', 'MGTSP.ME'),
(546, 'Kilroy Realty Corp REIT' ,'KRC', 'KRC'),
(547, 'B&G Foods Inc' ,'BGS', 'BGS'),
(548, 'Las Vegas Sands Corp' ,'LVS', 'LVS'),
(549, 'Pacira BioSciences Inc' ,'PCRX', 'PCRX'),
(550, 'Li Auto' ,'LI', 'LI'),
(551, 'Viasat' ,'VSAT', 'VSAT'),
(552, 'SS&C Technologies Holdings Inc' ,'SSNC', 'SSNC'),
(553, 'JOYY Inc' ,'YY', 'YY'),
(554, 'Arista Networks Inc' ,'ANET', 'ANET'),
(555, 'Hub Group Inc' ,'HUBG', 'HUBG'),
(556, 'eBay' ,'EBAY', 'EBAY'),
(557, 'Steel Dynamics Inc' ,'STLD', 'STLD'),
(558, 'Сбер Банк' ,'SBER', 'SBER.ME'),
(559, 'Ecolab' ,'ECL', 'ECL'),
(560, 'Appian Corp' ,'APPN', 'APPN'),
(561, 'Cadence Design Systems' ,'CDNS', 'CDNS'),
(562, 'Infineon Technologies AG' ,'IFX@DE', 'IFX.DE'),
(563, 'MSC Industrial Direct Co Inc' ,'MSM', 'MSM'),
(564, 'DaVita HealthCare Partners' ,'DVA', 'DVA'),
(565, 'PACCAR' ,'PCAR', 'PCAR'),
(566, 'PetroChina' ,'PTR', 'PTR'),
(567, 'Health Insurance Innovations' ,'HIIQ', '-'),
(568, 'O''Reilly Automotive' ,'ORLY', 'ORLY'),
(569, 'Affirm Holdings' ,'AFRM', 'AFRM'),
(570, 'AptarGroup' ,'ATR', 'ATR'),
(571, 'FARO Technologies Inc' ,'FARO', 'FARO'),
(572, 'Molina Healthcare Inc' ,'MOH', 'MOH'),
(573, 'IDACORP, Inc.' ,'IDA', 'IDA'),
(574, 'Ralph Lauren' ,'RL', 'RL'),
(575, 'Coupa Software Inc' ,'COUP', 'COUP'),
(576, 'Novavax' ,'NVAX', 'NVAX'),
(577, 'ATN International, Inc' ,'ATNI', 'ATNI'),
(578, 'Covestro AG' ,'1COV@DE', '1COV.DE'),
(579, 'Simon Property Group REIT' ,'SPG', 'SPG'),
(580, 'Sprouts Farmers Market Inc' ,'SFM', 'SFM'),
(581, 'Realty Income REIT' ,'O', 'O'),
(582, 'Artisan Partners Asset Management' ,'APAM', 'APAM'),
(583, 'LiveRamp Holdings Inc' ,'RAMP', 'RAMP'),
(584, 'Hyatt Hotels Corp' ,'H', 'H'),
(585, 'C3.ai, Inc' ,'AI', 'AI'),
(586, 'Compugen' ,'CGEN', 'CGEN'),
(587, 'Apartment Investment & Management' ,'AIV_old', 'AIV'),
(588, 'Gaming and Leisure Properties REIT' ,'GLPI', 'GLPI'),
(589, 'Fisker' ,'FSR', 'FSR'),
(590, 'FIBROGEN INC' ,'FGEN', 'FGEN'),
(591, 'Amazon.com' ,'AMZN', 'AMZN'),
(592, 'ФосАгро' ,'PHOR', 'PHOR.ME'),
(593, 'Polaris Industries Inc' ,'PII', 'PII'),
(594, 'Unity Software' ,'U', 'U'),
(595, 'ЧЗПСН' ,'PRFN', '-'),
(596, 'СОЛЛЕРС' ,'SVAV', 'SVAV.ME'),
(597, 'Manchester United Plc' ,'MANU', 'MANU'),
(598, 'Qualtrics International Inc.' ,'XM', 'XM'),
(599, 'Viatris Inc' ,'VTRS', 'VTRS'),
(600, 'Envestnet Inc' ,'ENV', 'ENV'),
(601, 'Innovative Industrial Properties REIT' ,'IIPR', 'IIPR'),
(602, 'Turning Point Therapeutics Inc' ,'TPTX', 'TPTX'),
(603, 'Dropbox Inc' ,'DBX', 'DBX'),
(604, 'PJT Partners Inc.' ,'PJT', 'PJT'),
(605, 'Объединенная авиастроительная корпорация' ,'UNAC', 'UNAC.ME'),
(606, 'Иркутскэнерго' ,'IRGZ', 'IRGZ.ME'),
(607, 'First Industrial REIT' ,'FR', 'FR'),
(608, 'Sanofi' ,'SNY', 'SNY'),
(609, 'NMI Holdings Inc' ,'NMIH', 'NMIH'),
(610, 'Box Inc' ,'BOX', 'BOX'),
(611, 'East West Ban' ,'EWBC', 'EWBC'),
(612, 'FLIR Systems' ,'FLIR', '-'),
(613, 'Ionis Pharmaceuticals Inc' ,'IONS', 'IONS'),
(614, 'Anthem' ,'ANTM', 'ANTM'),
(615, 'GXO Logistics, Inc.' ,'GXO', 'GXO'),
(616, 'Hawaiian Holdings Inc' ,'HA', 'HA'),
(617, 'Seacoast Banking Corp of Flori' ,'SBCF', 'SBCF'),
(618, 'Ziff Davis' ,'ZD', 'ZD'),
(619, 'Stem' ,'STEM', 'STEM'),
(620, 'XPEL' ,'XPEL', 'XPEL'),
(621, 'Ingredion Inc' ,'INGR', 'INGR'),
(622, 'Hilton Grand Vacations Inc' ,'HGV', 'HGV'),
(623, 'Tyler Technologies Inc' ,'TYL', 'TYL'),
(624, 'Avantor Inc' ,'AVTR', 'AVTR'),
(625, 'Xcel Energy' ,'XEL', 'XEL'),
(626, 'Etsy Inc' ,'ETSY', 'ETSY'),
(627, 'Kratos Defense & Security Solutions' ,'KTOS', 'KTOS'),
(628, 'DXC Technology' ,'DXC', 'DXC'),
(629, 'Leggett & Platt' ,'LEG', 'LEG'),
(630, 'Tradeweb Markets' ,'TW', 'TW'),
(631, 'Aurinia Pharmaceuticals' ,'AUPH', 'AUPH'),
(632, 'Resideo Technologies Inc' ,'REZI', 'REZI'),
(633, 'Medical Properties REIT' ,'MPW', 'MPW'),
(634, 'Siemens Healthineers AG' ,'SHL@DE', 'SHL.DE'),
(635, 'Onto Innovation Inc' ,'ONTO', 'ONTO'),
(636, 'Synaptics Inc' ,'SYNA', 'SYNA'),
(637, 'KKR & Co. Inc.' ,'KKR', 'KKR'),
(638, 'Zoetis' ,'ZTS', 'ZTS'),
(639, 'IAA, Inc.' ,'IAA', 'IAA'),
(640, 'Turtle Beach Corp' ,'HEAR', 'HEAR'),
(641, 'Silgan Holdings Inc.' ,'SLGN', 'SLGN'),
(642, 'First Citizens BancShares, Inc.' ,'FCNCA', 'FCNCA'),
(643, 'Meritor Inc' ,'MTOR', 'MTOR'),
(644, 'PriceSmart, Inc.' ,'PSMT', 'PSMT'),
(645, 'Amphenol' ,'APH', 'APH'),
(646, 'JPMorgan' ,'JPM', 'JPM'),
(647, 'Pitney Bowes' ,'PBI', 'PBI'),
(648, 'Euronet Worldwide Inc' ,'EEFT', 'EEFT'),
(649, 'Canadian National Railway Co' ,'CNI', 'CNR.TO'),
(650, 'Guidewire Software Inc' ,'GWRE', 'GWRE'),
(651, 'Veeva Systems Inc' ,'VEEV', 'VEEV'),
(652, 'Alexion Pharmaceuticals' ,'ALXN', '-'),
(653, 'Americold REIT' ,'COLD', 'COLD'),
(654, 'Marcus & Millichap Inc' ,'MMI', 'MMI'),
(655, 'MTU Aero Engines AG' ,'MTX@DE', 'MTX.DE'),
(656, 'Brown & Brown' ,'BRO', 'BRO'),
(657, 'Kemper' ,'KMPR', 'KMPR'),
(658, 'The Home Depot' ,'HD', 'HD'),
(659, 'Vista Outdoor' ,'VSTO', 'VSTO'),
(660, 'Constellation Brands' ,'STZ', 'STZ'),
(661, 'Русполимет' ,'RUSP', '-'),
(662, 'Medifast Inc' ,'MED', 'MED'),
(663, 'CloudFlare Inc' ,'NET', 'NET'),
(664, 'AtriCure' ,'ATRC', 'ATRC'),
(665, 'Allogene Therapeutics Inc' ,'ALLO', 'ALLO'),
(666, 'National Oilwell Varco' ,'NOV_old', 'NOV'),
(667, 'Southwestern Energy' ,'SWN', 'SWN'),
(668, 'SentinelOne, Inc.' ,'S', 'S'),
(669, 'TreeHouse Foods Inc' ,'THS', 'THS'),
(670, 'Red Rock Resorts' ,'RRR', 'RRR'),
(671, 'Sistema PJSFC' ,'SSA@GS', 'SSA.IL'),
(672, 'CSW Industrials Inc' ,'CSWI', 'CSWI'),
(673, 'Cinemark Holdings Inc' ,'CNK', 'CNK'),
(674, 'Altria Group' ,'MO', 'MO'),
(675, 'Wayfair Inc' ,'W', 'W'),
(676, 'Marvell Technology, Inc.' ,'MRVL', 'MRVL'),
(677, 'EMCOR Group' ,'EME', 'EME'),
(678, '1Life Healthcare' ,'ONEM', 'ONEM'),
(679, 'Confluent' ,'CFLT', 'CFLT'),
(680, 'Lumentum Holdings Inc' ,'LITE', 'LITE'),
(681, 'CEVA' ,'CEVA', 'CEVA'),
(682, 'Bentley Systems' ,'BSY', 'BSY'),
(683, 'Arconic' ,'ARNC', 'ARNC'),
(684, 'Krystal Biotech Inc' ,'KRYS', 'KRYS'),
(685, 'Snap Inc' ,'SNAP', 'SNAP'),
(686, 'CSG Systems International Inc' ,'CSGS', 'CSGS'),
(687, 'South Jersey Industries, Inc' ,'SJI', 'SJI'),
(688, 'AppLovin Corporation' ,'APP', 'APP'),
(689, 'Affiliated Managers Group' ,'AMG', 'AMG'),
(690, 'Corcept Therapeutics Inc' ,'CORT', 'CORT'),
(691, 'Alamo Group Inc.' ,'ALG', 'ALG'),
(692, 'PBF Energy Inc' ,'PBF', 'PBF'),
(693, 'Range Resources' ,'RRC', 'RRC'),
(694, 'Tyson Foods' ,'TSN', 'TSN'),
(695, 'Central Garden & Pet Co' ,'CENTA', 'CENTA'),
(696, 'Greenbrier Cos Inc' ,'GBX', 'GBX'),
(697, 'CommVault Systems Inc' ,'CVLT', 'CVLT'),
(698, 'Baker Hughes' ,'BKR', 'BKR'),
(699, 'AAON' ,'AAON', 'AAON'),
(700, 'Henkel AG & Co' ,'HEN3@DE', 'HEN3.DE'),
(701, 'Intellia Therapeutics Inc' ,'NTLA', 'NTLA'),
(702, 'Allison Transmission Holdings' ,'ALSN', 'ALSN'),
(703, 'Houlihan Lokey, Inc.' ,'HLI', 'HLI'),
(704, 'Roper Technologies' ,'ROP', 'ROP'),
(705, 'Steven Madden, Ltd.' ,'SHOO', 'SHOO'),
(706, 'Lennar' ,'LEN', 'LEN'),
(707, 'Ameren' ,'AEE', 'AEE'),
(708, 'Brink''s Co' ,'BCO', 'BCO'),
(709, 'Lancaster Colony' ,'LANC', 'LANC'),
(710, 'Vonage Holdings Corp' ,'VG', 'VG'),
(711, 'Snap-on' ,'SNA', 'SNA'),
(712, 'Karuna Therapeutics Inc' ,'KRTX', 'KRTX'),
(713, 'Spire Inc.' ,'SR', 'SR'),
(714, 'Community Bank System' ,'CBU', 'CBU'),
(715, 'Discovery Communications (B)' ,'DISCB', 'DISCB'),
(716, 'Fastenal Company' ,'FAST', 'FAST'),
(717, 'Zymergen Inc.' ,'ZY', 'ZY'),
(718, 'Alcoa Corporation' ,'AA', 'AA'),
(719, 'Cirrus Logic Inc' ,'CRUS', 'CRUS'),
(720, 'SelectQuote' ,'SLQT', 'SLQT'),
(721, 'Fiserv' ,'FISV', 'FISV'),
(722, 'SEI Investments Company' ,'SEIC', 'SEIC'),
(723, 'General Electric Company' ,'GE', 'GE'),
(724, 'MaxLinear Inc' ,'MXL', 'MXL'),
(725, 'Orion Office REIT' ,'ONL', 'ONL'),
(726, 'Neenah' ,'NP', 'NP'),
(727, 'PennyMac Financial Services' ,'PFSI', 'PFSI'),
(728, 'Kinder Morgan' ,'KMI', 'KMI'),
(729, 'Vectrus, Inc.' ,'VEC', 'VEC'),
(730, 'American Tower REIT' ,'AMT', 'AMT'),
(731, 'Coty' ,'COTY', 'COTY'),
(732, 'AppHarvest' ,'APPH', 'APPH'),
(733, 'Plexus Corp' ,'PLXS', 'PLXS'),
(734, 'Deutsche Boerse AG' ,'DB1@DE', 'DB1.DE'),
(735, 'Ball Corporation' ,'BLL', 'BLL'),
(736, 'Commercial Metals Company' ,'CMC', 'CMC'),
(737, 'Vaxart Inc' ,'VXRT', 'VXRT'),
(738, 'Hibbett, Inc.' ,'HIBB', 'HIBB'),
(739, 'AmerisourceBergen Corp' ,'ABC', 'ABC'),
(740, 'Voya Financial' ,'VOYA', 'VOYA'),
(741, 'Johnson Controls' ,'JCI', 'JCI'),
(742, 'AMN Healthcare Services Inc' ,'AMN', 'AMN'),
(743, 'Welltower REIT' ,'WELL', 'WELL'),
(744, 'Phillips 66' ,'PSX', 'PSX'),
(745, 'Intra-Cellular Therapies, Inc' ,'ITCI', 'ITCI'),
(746, 'Watsco Inc' ,'WSO', 'WSO'),
(747, 'HEICO' ,'HEI', 'HEI'),
(748, 'Bed Bath & Beyond' ,'BBBY', 'BBBY'),
(749, 'Silicon Laboratories Inc' ,'SLAB', 'SLAB'),
(750, 'CNH Industrial N.V.' ,'CNHI', 'CNHI'),
(751, 'Williams-Sonoma Inc' ,'WSM', 'WSM'),
(752, 'Benefytt Technologies' ,'BFYT', '-'),
(753, 'HP' ,'HPQ', 'HPQ'),
(754, 'Renewable Energy Group Inc' ,'REGI', 'REGI'),
(755, 'GoPro' ,'GPRO', 'GPRO'),
(756, 'AdvanSix Inc' ,'ASIX', 'ASIX'),
(757, 'Toyota Motor Corp' ,'TM', 'TM'),
(758, 'Gray Television Inc' ,'GTN', 'GTN'),
(759, 'COCA-COLA' ,'KO', 'KO'),
(760, 'Melco Resorts & Entertainment' ,'MLCO', 'MLCO'),
(761, 'Markel Corp' ,'MKL', 'MKL'),
(762, 'American Airlines Group' ,'AAL', 'AAL'),
(763, 'Red Robin Gourmet Burgers Inc' ,'RRGB', 'RRGB'),
(764, 'Philip Morris' ,'PM', 'PM'),
(765, 'Colgate-Palmolive' ,'CL', 'CL'),
(766, 'Agnico Eagle Mines' ,'AEM', 'AEM'),
(767, 'EQT Corporation' ,'EQT', 'EQT'),
(768, 'QuinStreet Inc' ,'QNST', 'QNST'),
(769, 'Ашинский метзавод' ,'AMEZ', 'AMEZ.ME'),
(770, 'Детский Мир' ,'DSKY', 'DSKY.ME'),
(771, 'Wolfspeed' ,'WOLF', 'WOLF'),
(772, 'Uber' ,'UBER', 'UBER'),
(773, 'PerkinElmer' ,'PKI', 'PKI'),
(774, 'Middlesex Water Company' ,'MSEX', 'MSEX'),
(775, 'UniFirst Corp MA' ,'UNF', 'UNF'),
(776, 'ConocoPhillips' ,'COP', 'COP'),
(777, 'Interactive Brokers Group Inc' ,'IBKR', 'IBKR'),
(778, 'Arrow Electronics Inc' ,'ARW', 'ARW'),
(779, 'Tractor Supply' ,'TSCO', 'TSCO'),
(780, 'Garmin' ,'GRMN', 'GRMN'),
(781, 'Duluth Holdings Inc' ,'DLTH', 'DLTH'),
(782, 'Lithium Americas Corp.' ,'LAC', 'LAC.TO'),
(783, 'Sabra Health Care REIT' ,'SBRA', 'SBRA'),
(784, 'CarMax' ,'KMX', 'KMX'),
(785, 'Owens Corning' ,'OC', 'OC'),
(786, 'World Wrestling Entertainment' ,'WWE', 'WWE'),
(787, 'ICICI Bank' ,'IBN', 'IBN'),
(788, 'Arvinas Inc' ,'ARVN', 'ARVN'),
(789, 'TechnipFMC' ,'FTI', 'FTI'),
(790, 'Quotient Technology Inc' ,'QUOT', 'QUOT'),
(791, 'Natus Medical Inc' ,'NTUS', 'NTUS'),
(792, 'Glaukos Corp' ,'GKOS', 'GKOS'),
(793, 'Rocket Lab' ,'RKLB', 'RKLB'),
(794, 'Anaplan Inc' ,'PLAN', 'PLAN'),
(795, 'Waste Management' ,'WM', 'WM'),
(796, 'Valmont Industries' ,'VMI', 'VMI'),
(797, 'John Bean Technologies' ,'JBT', 'JBT'),
(798, 'Qualcomm' ,'QCOM', 'QCOM'),
(799, 'Applied Therapeutics' ,'APLT', 'APLT'),
(800, 'Inari Medical Inc' ,'NARI', 'NARI'),
(801, 'CRISPR Therapeutics AG' ,'CRSP', 'CRSP'),
(802, 'Masimo Corporation' ,'MASI', 'MASI'),
(803, 'Trupanion Inc' ,'TRUP', 'TRUP'),
(804, 'Illumina' ,'ILMN', 'ILMN'),
(805, 'Graphic Packaging Holding Company' ,'GPK', 'GPK'),
(806, 'YETI Holdings Inc' ,'YETI', 'YETI'),
(807, 'National Fuel Gas Company' ,'NFG', 'NFG'),
(808, 'Virtu Financial, Inc.' ,'VIRT', 'VIRT'),
(809, 'SL Green REIT' ,'SLG', 'SLG'),
(810, 'Dick''s Sporting Goods Inc' ,'DKS', 'DKS'),
(811, 'Rivian Automotive' ,'RIVN', 'RIVN'),
(812, 'МРСК Юга' ,'MRKY', 'MRKY.ME'),
(813, 'ГДР En+ Group' ,'ENPL', 'ENPL.IL'),
(814, 'Snowflake Inc' ,'SNOW', 'SNOW'),
(815, 'Hello Group' ,'MOMO', 'MOMO'),
(816, 'ГДР Kaspi.kz JSC' ,'KSPI@GS', 'KSPI.IL'),
(817, 'Azenta' ,'AZTA', 'AZTA'),
(818, 'Kodiak Sciences Inc' ,'KOD', 'KOD'),
(819, 'Church & Dwight' ,'CHD', 'CHD'),
(820, 'Equity LifeStyle Properties REIT' ,'ELS', 'ELS'),
(821, 'TPG' ,'TPG', 'TPG'),
(822, 'VF' ,'VFC', 'VFC'),
(823, 'MongoDB Inc' ,'MDB', 'MDB'),
(824, 'Stryker' ,'SYK', 'SYK'),
(825, 'Sangamo Therapeutics' ,'SGMO', 'SGMO'),
(826, 'Eastman Chemical Company' ,'EMN', 'EMN'),
(827, 'Leidos Holdings' ,'LDOS', 'LDOS'),
(828, 'DoubleVerify Holdings, Inc.' ,'DV', 'DV'),
(829, 'Novartis AG' ,'NVS', 'NVS'),
(830, 'Loews' ,'L', 'L'),
(831, 'Logitech International SA' ,'LOGI', 'LOGN.SW'),
(832, 'ОВК' ,'UWGN', '-'),
(833, 'Iridium Communications Inc' ,'IRDM', 'IRDM'),
(834, 'LGI Homes Inc' ,'LGIH', 'LGIH'),
(835, 'Anterix' ,'ATEX', 'ATEX'),
(836, 'WestRock' ,'WRK', 'WRK'),
(837, 'OSI Systems Inc' ,'OSIS', 'OSIS'),
(838, 'MSA Safety' ,'MSA', 'MSA'),
(839, 'BJ''s Restaurants Inc' ,'BJRI', 'BJRI'),
(840, 'Sylvamo Corp.' ,'SLVM', 'SLVM'),
(841, 'Twilio Inc' ,'TWLO', 'TWLO'),
(842, 'Universal Health Services' ,'UHS', 'UHS'),
(843, 'Jabil Inc.' ,'JBL', 'JBL'),
(844, 'CNX Resources Corporation' ,'CNX', 'CNX'),
(845, 'Texas Instruments' ,'TXN', 'TXN'),
(846, 'United Airlines Holdings' ,'UAL', 'UAL'),
(847, 'United medical group' ,'GEMC', 'GEMC.ME'),
(848, 'Tetra Tech' ,'TTEK', 'TTEK'),
(849, 'Henry Schein' ,'HSIC', 'HSIC'),
(850, 'TopBuild Corp' ,'BLD', 'BLD'),
(851, 'Белуга Групп ПАО ао' ,'BELU', 'BELU.ME'),
(852, 'OneMain Holdings' ,'OMF', 'OMF'),
(853, 'CEL SCI Corporation' ,'CVM', 'CVM'),
(854, 'Maravai LifeSciences Holdings' ,'MRVI', 'MRVI'),
(855, 'Mallinckrodt PLC' ,'MNK', 'MNKKQ'),
(856, 'Consensus Cloud Solutions' ,'CCSI', 'CCSI'),
(857, 'Marathon Petroleum' ,'MPC', 'MPC'),
(858, 'S&P Global' ,'SPGI', 'SPGI'),
(859, 'Hubbell' ,'HUBB', 'HUBB'),
(860, 'Editas Medicine Inc' ,'EDIT', 'EDIT'),
(861, 'Builders FirstSource Inc' ,'BLDR', 'BLDR'),
(862, 'Lincoln Electric Holdings' ,'LECO', 'LECO'),
(863, 'НКХП' ,'NKHP', 'NKHP.ME'),
(864, 'Palantir Technologies Inc' ,'PLTR', 'PLTR'),
(865, 'Fresenius SE' ,'FRE@DE', 'FRE.DE'),
(866, 'Delivery Hero SE' ,'DHER@DE', 'DHER.DE'),
(867, 'Sinclair Broadcast Group Inc' ,'SBGI', 'SBGI'),
(868, 'Generac Holdings Inc' ,'GNRC', 'GNRC'),
(869, 'Arch Capital Group' ,'ACGL', 'ACGL'),
(870, 'Harley-Davidson' ,'HOG', 'HOG'),
(871, 'Blackbaud Inc' ,'BLKB', 'BLKB'),
(872, 'American Express' ,'AXP', 'AXP'),
(873, 'Procore Technologies' ,'PCOR', 'PCOR'),
(874, 'MicroVision' ,'MVIS', 'MVIS'),
(875, 'Sony Corp' ,'SONY', 'SONY'),
(876, 'Howard Hughes Corp' ,'HHC', 'HHC'),
(877, 'Amicus Therapeutics' ,'FOLD', 'FOLD'),
(878, 'Dril-Quip Inc' ,'DRQ', 'DRQ'),
(879, 'Norfolk Southern' ,'NSC', 'NSC'),
(880, 'JM Smucker' ,'SJM', 'SJM'),
(881, 'Dollar Tree' ,'DLTR', 'DLTR'),
(882, 'Alphabet Class C' ,'GOOG', 'GOOG'),
(883, 'Cintas' ,'CTAS', 'CTAS'),
(884, 'Prudential Financial' ,'PRU', 'PRU'),
(885, 'KLA-Tencor' ,'KLAC', 'KLAC'),
(886, 'LCI Industries' ,'LCII', 'LCII'),
(887, 'Центральный Телеграф - акции привилегированные' ,'CNTLP', 'CNTLP.ME'),
(888, 'Kulicke & Soffa Industries' ,'KLIC', 'KLIC'),
(889, 'Franklin Resources' ,'BEN', 'BEN'),
(890, 'Credit Acceptance Corp' ,'CACC', 'CACC'),
(891, 'Berry Global Group Inc' ,'BERY', 'BERY'),
(892, 'Borussia Dortmund GmbH & Co KG' ,'BVB@DE', 'BVB.DE'),
(893, 'Globaltrans Investment PLC' ,'GLTR', 'GLTR.IL'),
(894, 'Sprout Social' ,'SPT', 'SPT'),
(895, 'Jack Henry & Associates Inc' ,'JKHY', 'JKHY'),
(896, 'Forward Air Corporation' ,'FWRD', 'FWRD'),
(897, 'Teladoc Health Inc' ,'TDOC', 'TDOC'),
(898, 'Paylocity Holding Corp' ,'PCTY', 'PCTY'),
(899, 'Washington Federal, Inc.' ,'WAFD', 'WAFD'),
(900, 'T-Mobile US Inc' ,'TMUS', 'TMUS'),
(901, 'Goldman Sachs' ,'GS', 'GS'),
(902, 'Hannon Armstrong REIT' ,'HASI', 'HASI'),
(903, 'China Mobile' ,'CHL', '-'),
(904, 'Post Holdings Inc' ,'POST', 'POST'),
(905, 'Globus Medical Inc' ,'GMED', 'GMED'),
(906, 'Conagra Brands' ,'CAG', 'CAG'),
(907, 'Mastercard' ,'MA', 'MA'),
(908, 'American International Group' ,'AIG', 'AIG'),
(909, 'Omnicom Group' ,'OMC', 'OMC'),
(910, 'ГДР X5 RetailGroup' ,'FIVE', 'FIVE.IL'),
(911, 'Ultra Clean Holdings Inc' ,'UCTT', 'UCTT'),
(912, 'Virtus Investment Partners' ,'VRTS', 'VRTS'),
(913, 'Oil States International Inc' ,'OIS', 'OIS'),
(914, 'Madison Square Garden Co' ,'MSGS', 'MSGS'),
(915, 'Weibo Corporation' ,'WB', 'WB'),
(916, 'Ryder System' ,'R', 'R'),
(917, 'LKQ Corporation' ,'LKQ', 'LKQ'),
(918, 'Bilibili Inc' ,'BILI', 'BILI'),
(919, 'Coherent Inc' ,'COHR', 'COHR'),
(920, 'Innospec' ,'IOSP', 'IOSP'),
(921, 'Teradyne Inc' ,'TER', 'TER'),
(922, 'Cooper-Standard Holdings Inc' ,'CPS', 'CPS'),
(923, 'The Beauty Health Company' ,'SKIN', 'SKIN'),
(924, 'АДР SAP' ,'SAP', 'SAPA.F'),
(925, 'Starbucks Corporation' ,'SBUX', 'SBUX'),
(926, 'Башнефть' ,'BANE', 'BANE.ME'),
(927, 'Caterpillar' ,'CAT', 'CAT'),
(928, 'O''Key Group SA' ,'OKEY', 'OKEY.IL'),
(929, 'Trex Co Inc' ,'TREX', 'TREX'),
(930, 'Integra LifeSciences Holdings' ,'IART', 'IART'),
(931, 'Rogers Corp' ,'ROG', 'ROG'),
(932, 'PayPal Holdings' ,'PYPL', 'PYPL'),
(933, 'SONOS INC' ,'SONO', 'SONO'),
(934, 'Crown Castle REIT' ,'CCI', 'CCI'),
(935, 'American Eagle Outfitters Inc' ,'AEO', 'AEO'),
(936, 'Nexstar Media Group Inc' ,'NXST', 'NXST'),
(937, 'CVS Health Corporation' ,'CVS', 'CVS'),
(938, 'NeoGenomics Inc' ,'NEO', 'NEO'),
(939, 'HCA Healthcare' ,'HCA', 'HCA'),
(940, 'TuSimple Holdings' ,'TSP', 'TSP'),
(941, 'Independent Bank Group, Inc.' ,'IBTX', 'IBTX'),
(942, 'Polyus PJSC' ,'PLZL@GS', 'PLZL.IL'),
(943, 'UDR REIT' ,'UDR', 'UDR'),
(944, 'United Parcel Service' ,'UPS', 'UPS'),
(945, 'Arthur J. Gallagher & Co' ,'AJG', 'AJG'),
(946, 'Yum China Holdings' ,'YUMC', 'YUMC'),
(947, 'RenaissanceRe Holdings' ,'RNR', 'RNR'),
(948, 'Novatek PJSC' ,'NVTK@GS', 'NVTK.IL'),
(949, 'Трубная Металлургическая Компания' ,'TRMK', 'TRMK.ME'),
(950, 'Siemens AG' ,'SIE@DE', 'SIE.DE'),
(951, 'Positive Technologies' ,'POSI', 'POSI.ME'),
(952, 'Cavco Industries Inc' ,'CVCO', 'CVCO'),
(953, 'Rollins' ,'ROL', 'ROL'),
(954, 'Башнефть - привилегированные акции' ,'BANEP', 'BANEP.ME'),
(955, 'Wells Fargo & Company' ,'WFC', 'WFC'),
(956, 'LPL Financial Holdings' ,'LPLA', 'LPLA'),
(957, 'РУСАЛ' ,'RUAL', '0486.HK'),
(958, 'Charles River Laboratories Int' ,'CRL', 'CRL'),
(959, 'Nevro' ,'NVRO', 'NVRO'),
(960, 'Malibu Boats Inc' ,'MBUU', 'MBUU'),
(961, 'Boot Barn Holdings Inc' ,'BOOT', 'BOOT'),
(962, 'FedEx' ,'FDX', 'FDX'),
(963, 'Waters' ,'WAT', 'WAT'),
(964, 'Chart Industries Inc' ,'GTLS', 'GTLS'),
(965, 'Rapid7 Inc' ,'RPD', 'RPD'),
(966, 'Oak Street Health' ,'OSH', 'OSH'),
(967, 'Velodyne Lidar' ,'VLDR', 'VLDR'),
(968, 'Signet Jewelers' ,'SIG', 'SIG'),
(969, 'Hartford Financial Services' ,'HIG', 'HIG'),
(970, 'Madison Square Garden Entertainment' ,'MSGE', 'MSGE'),
(971, 'Capital One' ,'COF', 'COF'),
(972, 'Таттелеком' ,'TTLK', 'TTLK.ME'),
(973, 'Fifth Third Bancorp' ,'FITB', 'FITB'),
(974, 'Riot Blockchain' ,'RIOT', 'RIOT'),
(975, 'Chegg Inc' ,'CHGG', 'CHGG'),
(976, 'Yum!' ,'YUM', 'YUM'),
(977, 'Morgan Stanley' ,'MS', 'MS'),
(978, 'Xilinx' ,'XLNX', 'XLNX'),
(979, 'Nasdaq' ,'NDAQ', 'NDAQ'),
(980, 'SolarEdge Technologies Inc' ,'SEDG', 'SEDG'),
(981, 'Норильский никель' ,'GMKN', 'GMKN.ME'),
(982, 'Methode Electronics Inc' ,'MEI', 'MEI'),
(983, 'Gevo' ,'GEVO', 'GEVO'),
(984, 'Repligen Corporation' ,'RGEN', 'RGEN'),
(985, 'SPX FLOW Inc' ,'FLOW', 'FLOW'),
(986, 'Sempra Energy' ,'SRE', 'SRE'),
(987, 'OGE Energy Corp.' ,'OGE', 'OGE'),
(988, 'Teleflex Inc' ,'TFX', 'TFX'),
(989, 'Hewlett Packard Enterprise' ,'HPE', 'HPE'),
(990, 'WP Carey REIT' ,'WPC', 'WPC'),
(991, 'IBM' ,'IBM', 'IBM'),
(992, 'Calavo Growers Inc' ,'CVGW', 'CVGW'),
(993, 'NetScout Systems Inc' ,'NTCT', 'NTCT'),
(994, 'Ciena Corp' ,'CIEN', 'CIEN'),
(995, 'Digital Realty REIT' ,'DLR', 'DLR'),
(996, 'SL Green Realty' ,'SLG_old', 'SLG'),
(997, 'Brighthouse Financial' ,'BHF', 'BHF'),
(998, 'Smith & Wesson Brands' ,'SWBI', 'SWBI'),
(999, 'Glacier Ban' ,'GBCI', 'GBCI'),
(1000, 'МОЭСК' ,'MSRS', 'MSRS.ME'),
(1001, 'Envista Holdings' ,'NVST', 'NVST'),
(1002, 'Zillow Group Inc' ,'Z', 'Z'),
(1003, 'Selective Insurance Group' ,'SIGI', 'SIGI'),
(1004, 'Tempur Sealy International Inc' ,'TPX', 'TPX'),
(1005, 'New York Community Bancorp' ,'NYCB', 'NYCB'),
(1006, 'QIWI' ,'QIWI', 'QIWI'),
(1007, 'Woodward Inc' ,'WWD', 'WWD'),
(1008, 'Корпорация ИРКУТ' ,'IRKT', 'IRKT.ME'),
(1009, 'DermTech' ,'DMTK', 'DMTK'),
(1010, 'Neogen Corp' ,'NEOG', 'NEOG'),
(1011, 'ИСКЧ' ,'ISKJ', 'ISKJ.ME'),
(1012, 'NuVasive Inc' ,'NUVA', 'NUVA'),
(1013, 'Apple Hospitality REIT' ,'APLE', 'APLE'),
(1014, 'Choice Hotels International In' ,'CHH', 'CHH'),
(1015, 'Vitesco Technologies Group AG' ,'VTSC@DE', 'VTSC.DE'),
(1016, 'Ozon Holdings PLC' ,'OZON', 'OZON'),
(1017, 'Virgin Galactic Holdings Inc Class A' ,'SPCE', 'SPCE'),
(1018, 'Volkswagen AG' ,'VOW3@DE', 'VOW3.DE'),
(1019, 'F5' ,'FFIV', 'FFIV'),
(1020, 'Group 1 Automotive Inc' ,'GPI', 'GPI'),
(1021, 'Equifax' ,'EFX', 'EFX'),
(1022, 'Spotify Technology SA' ,'SPOT', 'SPOT'),
(1023, 'Alexandria Real Estate Equities REIT' ,'ARE', 'ARE'),
(1024, 'Chemours Company' ,'CC', 'CC'),
(1025, 'TaskUs' ,'TASK', 'TASK'),
(1026, 'Q2 Holdings Inc' ,'QTWO', 'QTWO'),
(1027, 'Splunk' ,'SPLK', 'SPLK'),
(1028, 'Automatic Data Processing' ,'ADP', 'ADP'),
(1029, 'Erie IndemnIty Co' ,'ERIE', 'ERIE'),
(1030, 'ZoomInfo Technologies Inc' ,'ZI', 'ZI'),
(1031, 'Юнипро' ,'UPRO', 'UPRO.ME'),
(1032, 'SouthState Corp' ,'SSB', 'SSB'),
(1033, 'Timken Co The' ,'TKR', 'TKR'),
(1034, 'Reliance Steel & Aluminum Co' ,'RS', 'RS'),
(1035, 'Vuzix Corp' ,'VUZI', 'VUZI'),
(1036, 'M.D.C. Holdings' ,'MDC', 'MDC'),
(1037, 'Guardant Health Inc' ,'GH', 'GH'),
(1038, 'AstraZeneca PLC' ,'AZN', 'AZN'),
(1039, 'Deciphera Pharmaceuticals Inc' ,'DCPH', 'DCPH'),
(1040, 'Micro Focus' ,'MFGP', 'MFGP'),
(1041, 'Exxon Mobil Corporation' ,'XOM', 'XOM'),
(1042, 'Aspira Womens Health' ,'AWH', 'AWH'),
(1043, 'Shake Shack Inc' ,'SHAK', 'SHAK'),
(1044, 'TotalEnergies SE' ,'TOT', '-'),
(1045, 'Iovance Biotherapeutics Inc' ,'IOVA', 'IOVA'),
(1046, 'PVH' ,'PVH', 'PVH'),
(1047, 'Nikola' ,'NKLA', 'NKLA'),
(1048, 'Alaska Air Group' ,'ALK', 'ALK'),
(1049, 'Royal Bank of Canada' ,'RY', 'RY.TO'),
(1050, 'West Pharmaceutical Services I' ,'WST', 'WST'),
(1051, 'Мечел - Привилегированные акции' ,'MTLRP', 'MTLRP.ME'),
(1052, 'Schlumberger' ,'SLB', 'SLB'),
(1053, 'Frontdoor, Inc.' ,'FTDR', 'FTDR'),
(1054, 'T Rowe Price Group' ,'TROW', 'TROW'),
(1055, 'ПАО «КАЗАНЬОРГСИНТЕЗ» - акции привилегированные' ,'KZOSP', 'KZOSP.ME'),
(1056, 'SAP SE' ,'SAP@DE', 'SAP.DE'),
(1057, 'Ленэнерго' ,'LSNG', 'LSNG.ME'),
(1058, 'SYNNEX Corp' ,'SNX', 'SNX'),
(1059, 'РусГидро' ,'HYDR', 'HYDR.ME'),
(1060, 'Graphite Bio, Inc.' ,'GRPH', 'GRPH'),
(1061, 'Atrion Corp' ,'ATRI', 'ATRI'),
(1062, 'eXp World Holdings' ,'EXPI', 'EXPI'),
(1063, 'CMS Energy Corporation' ,'CMS', 'CMS'),
(1064, 'Inogen Inc' ,'INGN', 'INGN'),
(1065, 'Deutsche Lufthansa AG' ,'LHA@DE', 'LHA.DE'),
(1066, 'Vericel Corp' ,'VCEL', 'VCEL'),
(1067, 'Transocean' ,'RIG', 'RIG'),
(1068, 'Energizer Holdings Inc' ,'ENR', 'ENR'),
(1069, 'Parsons' ,'PSN', 'PSN'),
(1070, 'Manhattan Associates Inc' ,'MANH', 'MANH'),
(1071, 'Ростелеком - Привилегированные акции' ,'RTKMP', 'RTKMP.ME'),
(1072, 'ICON plc' ,'ICLR', 'ICLR'),
(1073, 'АФК Система' ,'AFKS', 'AFKS.ME'),
(1074, 'Fulcrum Therapeutics' ,'FULC', 'FULC'),
(1075, 'Monro' ,'MNRO', 'MNRO'),
(1076, 'Watts Water Technologies Inc' ,'WTS', 'WTS'),
(1077, 'ICU Medical Inc' ,'ICUI', 'ICUI'),
(1078, 'PROG Holdings' ,'PRG', 'PRG'),
(1079, 'NetEase Inc' ,'NTES', 'NTES'),
(1080, 'KnowBe4' ,'KNBE', 'KNBE'),
(1081, 'Viela Bio' ,'VIE', '-'),
(1082, 'Fluor' ,'FLR', 'FLR'),
(1083, 'ТНС энерго Воронеж' ,'VRSB', 'VRSB.ME'),
(1084, 'Global Blood Therapeutics Inc' ,'GBT', 'GBT'),
(1085, 'Altice USA Inc' ,'ATUS', 'ATUS'),
(1086, 'Takeda Pharmaceutical Co Ltd' ,'TAK', 'TAK'),
(1087, 'AutoZone' ,'AZO', 'AZO'),
(1088, 'ViacomCBS Inc.' ,'VIAC', 'VIAC'),
(1089, 'Workhorse Group Inc' ,'WKHS', 'WKHS'),
(1090, 'Delta Air Lines' ,'DAL', 'DAL'),
(1091, 'DLocal' ,'DLO', 'DLO'),
(1092, 'ANI Pharmaceuticals Inc' ,'ANIP', 'ANIP'),
(1093, 'Microsoft Corporation' ,'MSFT', 'MSFT'),
(1094, 'D.R. Horton' ,'DHI', 'DHI'),
(1095, 'nCino' ,'NCNO', 'NCNO'),
(1096, 'Fox Factory Holding Corp' ,'FOXF', 'FOXF'),
(1097, 'ACI Worldwide, Inc.' ,'ACIW', 'ACIW'),
(1098, 'WillScot Mobile Mini Holdings' ,'WSC', 'WSC'),
(1099, 'Роснефть' ,'ROSN', 'ROSN.ME'),
(1100, 'Нижнекамскнефтехим' ,'NKNC', 'NKNC.ME'),
(1101, 'Pan American Silver Corp' ,'PAAS', 'PAAS.TO'),
(1102, 'Moody''s' ,'MCO', 'MCO'),
(1103, 'Portland General Electric' ,'POR', 'POR'),
(1104, 'JFrog Ltd.' ,'FROG', 'FROG'),
(1105, 'Aon' ,'AON', 'AON'),
(1106, 'Energy Transfer LP' ,'ET', 'ET'),
(1107, 'Prosperity Bancshares' ,'PB', 'PB'),
(1108, 'United Therapeutics Corp' ,'UTHR', 'UTHR'),
(1109, 'PTC Therapeutics' ,'PTCT', 'PTCT'),
(1110, 'Nielsen Holdings plc' ,'NLSN', 'NLSN'),
(1111, 'Vertex Pharmaceuticals' ,'VRTX', 'VRTX'),
(1112, 'International Flavors & Fragrances' ,'IFF', 'IFF'),
(1113, 'Alibaba' ,'BABA', 'BABA'),
(1114, 'Ameriprise Financial' ,'AMP', 'AMP'),
(1115, 'AvalonBay Communities REIT' ,'AVB', 'AVB'),
(1116, 'Wix.com Ltd' ,'WIX', 'WIX'),
(1117, 'WR Berkley' ,'WRB', 'WRB'),
(1118, 'VEON' ,'VEON', 'VEON'),
(1119, 'Ares Capital Corp' ,'ARCC', 'ARCC'),
(1120, 'Hasbro' ,'HAS', 'HAS'),
(1121, 'Wingstop Inc' ,'WING', 'WING'),
(1122, 'Esperion Therapeutics Inc' ,'ESPR', 'ESPR'),
(1123, 'Urban Outfitters' ,'URBN', 'URBN'),
(1124, 'Global Net Lease REIT' ,'GNL', 'GNL'),
(1125, 'Parker-Hannifin' ,'PH', 'PH'),
(1126, 'Edison International' ,'EIX', 'EIX'),
(1127, 'Mettler Toledo' ,'MTD', 'MTD'),
(1128, 'Graco' ,'GGG', 'GGG'),
(1129, 'Solid Biosciences' ,'SLDB', 'SLDB'),
(1130, 'Albemarle' ,'ALB', 'ALB'),
(1131, 'KeyCorp' ,'KEY', 'KEY'),
(1132, 'Ally Financial Inc' ,'ALLY', 'ALLY'),
(1133, 'AeroVironment Inc' ,'AVAV', 'AVAV'),
(1134, 'Alliance Data Systems' ,'ADS', 'ADS'),
(1135, 'SJW Group' ,'SJW', 'SJW'),
(1136, 'Arcus Biosciences' ,'RCUS', 'RCUS'),
(1137, 'ICF International, Inc.' ,'ICFI', 'ICFI'),
(1138, 'Газпром' ,'GAZP', 'GAZP.ME'),
(1139, 'Lattice Semiconductor Corp' ,'LSCC', 'LSCC'),
(1140, 'MSCI Inc' ,'MSCI', 'MSCI'),
(1141, 'The Estee Lauder Companies' ,'EL', 'EL'),
(1142, 'Eagle Materials Inc' ,'EXP', 'EXP'),
(1143, 'LyondellBasell' ,'LYB', 'LYB'),
(1144, 'NAC Kazatomprom JSC' ,'KAP@GS', 'KAP.IL'),
(1145, 'Minerals Technologies Inc.' ,'MTX', 'MTX'),
(1146, 'BlackRock' ,'BLK', 'BLK'),
(1147, 'Саратовский НПЗ - акции привилегированные' ,'KRKNP', 'KRKNP.ME'),
(1148, 'ALLETE, Inc.' ,'ALE', 'ALE'),
(1149, 'Sherwin-Williams' ,'SHW', 'SHW'),
(1150, 'Kyndryl Holdings' ,'KD', 'KD'),
(1151, 'Baxter International' ,'BAX', 'BAX'),
(1152, 'Dollar General' ,'DG', 'DG'),
(1153, 'Chubb' ,'CB', 'CB'),
(1154, 'Badger Meter Inc' ,'BMI', 'BMI'),
(1155, 'Darden Restaurants' ,'DRI', 'DRI'),
(1156, 'Распадская' ,'RASP', 'RASP.ME'),
(1157, 'Boston Scientific Corporation' ,'BSX', 'BSX'),
(1158, 'IAC InterActiveCorp' ,'IAC', 'IAC'),
(1159, 'The Williams Companies' ,'WMB', 'WMB'),
(1160, 'Ultragenyx Pharmaceutical Inc' ,'RARE', 'RARE'),
(1161, 'Asbury Automotive Group Inc' ,'ABG', 'ABG'),
(1162, 'Vulcan Materials' ,'VMC', 'VMC'),
(1163, 'Sensient Technologies Corp' ,'SXT', 'SXT'),
(1164, 'Plug Power Inc' ,'PLUG', 'PLUG'),
(1165, 'Patterson' ,'PDCO', 'PDCO'),
(1166, 'Severstal PJSC' ,'SVST@GS', 'SVST.IL'),
(1167, 'Северсталь' ,'CHMF', 'CHMF.ME'),
(1168, 'ГДР Etalon Group PLC' ,'ETLN', 'ETLN.IL'),
(1169, 'Kaiser Aluminum Corp' ,'KALU', 'KALU'),
(1170, 'ГДР Softline' ,'SFTL', 'SFTL.IL'),
(1171, 'Vale SA' ,'VALE', 'VALE'),
(1172, 'Bruker Corp' ,'BRKR', 'BRKR'),
(1173, 'Saia Inc' ,'SAIA', 'SAIA'),
(1174, 'STERIS' ,'STE', 'STE'),
(1175, 'Becton, Dickinson and Company' ,'BDX', 'BDX'),
(1176, 'Российские сети - акции привилегированные' ,'RSTIP', 'RSTIP.ME'),
(1177, 'Raymond James Financial' ,'RJF', 'RJF'),
(1178, 'Tucows Inc' ,'TCX', 'TCX'),
(1179, 'China Telecom' ,'CHA', '-'),
(1180, 'The Aarons Company' ,'AAN', 'AAN'),
(1181, 'Fortive' ,'FTV', 'FTV'),
(1182, 'IHS Markit' ,'INFO', 'INFO'),
(1183, 'LifeStance Health Group' ,'LFST', 'LFST'),
(1184, 'MerIt Medical Systems Inc' ,'MMSI', 'MMSI'),
(1185, 'NETGEAR Inc' ,'NTGR', 'NTGR'),
(1186, 'Penske Automotive Group' ,'PAG', 'PAG'),
(1187, 'Texas Capital Bancshares Inc' ,'TCBI', 'TCBI'),
(1188, 'First Merchants Corporation' ,'FRME', 'FRME'),
(1189, 'Cowen, Inc.' ,'COWN', 'COWN'),
(1190, 'Vontier Corporation' ,'VNT', 'VNT'),
(1191, 'Qorvo' ,'QRVO', 'QRVO'),
(1192, 'Essential Utilities, Inc.' ,'WTRG', 'WTRG'),
(1193, 'АДР Just Eat Takeaway.com N.V.' ,'GRUB', 'GRUB'),
(1194, 'Lennox International Inc' ,'LII', 'LII'),
(1195, 'National Beverage Corp' ,'FIZZ', 'FIZZ'),
(1196, 'America''s Car-Mart Inc TX' ,'CRMT', 'CRMT'),
(1197, 'LHC Group Inc' ,'LHCG', 'LHCG'),
(1198, 'DraftKings Inc' ,'DKNG', 'DKNG'),
(1199, 'Movado Group Inc' ,'MOV', 'MOV'),
(1200, 'Stifel Financial' ,'SF', 'SF'),
(1201, 'United Bankshares, Inc.' ,'UBSI', 'UBSI'),
(1202, 'Zebra Technologies Corp' ,'ZBRA', 'ZBRA'),
(1203, 'Nektar Therapeutics' ,'NKTR', 'NKTR'),
(1204, 'Vishay Precision Group Inc' ,'VPG', 'VPG'),
(1205, 'Baozun Inc' ,'BZUN', 'BZUN'),
(1206, 'Intercontinental Exchange' ,'ICE', 'ICE'),
(1207, 'Squarespace, Inc.' ,'SQSP', 'SQSP'),
(1208, 'Cummins' ,'CMI', 'CMI'),
(1209, 'Comerica Incorporated' ,'CMA', 'CMA'),
(1210, 'Lear Corp' ,'LEA', 'LEA'),
(1211, 'Shockwave Medical Inc' ,'SWAV', 'SWAV'),
(1212, 'Vistra' ,'VST', 'VST'),
(1213, 'Freshpet Inc' ,'FRPT', 'FRPT'),
(1214, 'Qualys Inc' ,'QLYS', 'QLYS'),
(1215, 'Charter Communications' ,'CHTR', 'CHTR'),
(1216, 'Cigna' ,'CI', 'CI'),
(1217, 'Сбер Банк - привилегированные акции' ,'SBERP', 'SBERP.ME'),
(1218, 'Atkore International Group Inc' ,'ATKR', 'ATKR'),
(1219, 'Clarivate' ,'CLVT', 'CLVT'),
(1220, 'Cerence' ,'CRNC', 'CRNC'),
(1221, 'Petropavlovsk PLC' ,'POGR', 'POG.L'),
(1222, 'Varonis Systems Inc' ,'VRNS', 'VRNS'),
(1223, 'WESCO International Inc' ,'WCC', 'WCC'),
(1224, 'Hochtief AG' ,'HOT@DE', 'HOT.DE'),
(1225, 'Liberty Broadband Corporation' ,'LBRDK', 'LBRDK'),
(1226, 'Honeywell' ,'HON', 'HON'),
(1227, 'Life Storage REIT' ,'LSI', 'LSI'),
(1228, 'Lockheed Martin' ,'LMT', 'LMT'),
(1229, 'ModivCare Inc.' ,'MODV', 'MODV'),
(1230, 'Beyond Meat Inc' ,'BYND', 'BYND'),
(1231, 'Rayonier REIT' ,'RYN', 'RYN'),
(1232, 'DocuSign Inc' ,'DOCU', 'DOCU'),
(1233, 'AECOM' ,'ACM', 'ACM'),
(1234, 'Southwest Airlines' ,'LUV', 'LUV'),
(1235, 'Beacon Roofing Supply Inc' ,'BECN', 'BECN'),
(1236, 'Red River Bancshares' ,'RRBI', 'RRBI'),
(1237, 'Reynolds Consumer Products Inc.' ,'REYN', 'REYN'),
(1238, 'NovoCure Limited' ,'NVCR', 'NVCR'),
(1239, 'Canadian Pacific Railway' ,'CP', 'CP.TO'),
(1240, 'Brown-Forman' ,'BF.B', 'BF-B'),
(1241, 'ЧТПЗ' ,'CHEP', '-'),
(1242, 'Levi Strauss & Co' ,'LEVI', 'LEVI'),
(1243, 'Principal Financial Group' ,'PFG', 'PFG'),
(1244, 'IQVIA Holdings Inc' ,'IQV', 'IQV'),
(1245, 'Thomson Reuters Corporation' ,'TRI', 'TRI.TO'),
(1246, 'Lyft Inc' ,'LYFT', 'LYFT'),
(1247, 'Carter''s Inc' ,'CRI', 'CRI'),
(1248, 'Republic Services' ,'RSG', 'RSG'),
(1249, 'PRA Group Inc' ,'PRAA', 'PRAA'),
(1250, 'Sealed Air' ,'SEE', 'SEE'),
(1251, 'Arena Pharmaceuticals Inc' ,'ARNA', 'ARNA'),
(1252, 'Everest Re Group' ,'RE', 'RE'),
(1253, 'Dover' ,'DOV', 'DOV'),
(1254, 'Cardinal Health' ,'CAH', 'CAH'),
(1255, 'Cypress Semiconductor Corp' ,'CY', '-'),
(1256, 'CareDx Inc' ,'CDNA', 'CDNA'),
(1257, 'Marsh & McLennan' ,'MMC', 'MMC'),
(1258, 'Macerich REIT' ,'MAC', 'MAC'),
(1259, 'Jefferies Financial Group' ,'JEF', 'JEF'),
(1260, 'Motorola Solutions' ,'MSI', 'MSI'),
(1261, 'MP Materials' ,'MP', 'MP'),
(1262, 'Big Lots Inc' ,'BIG', 'BIG'),
(1263, 'Veracyte Inc' ,'VCYT', 'VCYT'),
(1264, 'AMD' ,'AMD', 'AMD'),
(1265, 'Fortune Brands Home & Security' ,'FBHS', 'FBHS'),
(1266, 'Cognex Corp' ,'CGNX', 'CGNX'),
(1267, 'Bridgebio Pharma' ,'BBIO', 'BBIO'),
(1268, 'ProPetro Holding Corp' ,'PUMP', 'PUMP'),
(1269, 'Fortinet Inc' ,'FTNT', 'FTNT'),
(1270, 'Riskified' ,'RSKD', 'RSKD'),
(1271, 'Helmerich & Payne' ,'HP', 'HP'),
(1272, 'Concentrix Corporation' ,'CNXC', 'CNXC'),
(1273, 'Wolverine World Wide Inc' ,'WWW', 'WWW'),
(1274, 'ZIM Integrated Shipping Services' ,'ZIM', 'ZIM'),
(1275, 'Garrett Motion Inc' ,'GTX', 'GTX'),
(1276, 'CBRE Group' ,'CBRE', 'CBRE'),
(1277, 'China Eastern Airlines' ,'CEA', 'CEA'),
(1278, 'FIGS' ,'FIGS', 'FIGS'),
(1279, 'Lantheus Holdings Inc' ,'LNTH', 'LNTH'),
(1280, 'IPG Photonics Corporation' ,'IPGP', 'IPGP'),
(1281, 'National Oilwell Varco' ,'NOV', 'NOV'),
(1282, 'Central Garden & Pet Co' ,'CENT', 'CENT'),
(1283, 'Doximity, Inc.' ,'DOCS', 'DOCS'),
(1284, 'Hormel Foods' ,'HRL', 'HRL'),
(1285, 'Grand Canyon Education Inc' ,'LOPE', 'LOPE'),
(1286, 'Cactus Inc' ,'WHD', 'WHD'),
(1287, 'Emergent BioSolutions Inc' ,'EBS', 'EBS'),
(1288, 'Regions Financial' ,'RF', 'RF'),
(1289, 'Andersons Inc' ,'ANDE', 'ANDE'),
(1290, 'Natura & Co Holding S.A.' ,'NTCO', 'NTCON.MX'),
(1291, 'Лента' ,'LENT', 'LENT.ME'),
(1292, 'National Presto Industries Inc' ,'NPK', 'NPK'),
(1293, 'US Bancorp' ,'USB', 'USB'),
(1294, 'Evotec AG' ,'EVT@DE', 'EVT.DE'),
(1295, 'General Mills' ,'GIS', 'GIS'),
(1296, 'Franklin Electric Co' ,'FELE', 'FELE'),
(1297, 'CDW Corp' ,'CDW', 'CDW'),
(1298, 'Aaron''s Inc' ,'AANold', 'AAN'),
(1299, 'Healthcare Services Group Inc' ,'HCSG', 'HCSG'),
(1300, 'Starwood Property Trust REIT' ,'STWD', 'STWD'),
(1301, 'Allegion' ,'ALLE', 'ALLE'),
(1302, 'PolyOne Corp' ,'POLold', '-'),
(1303, 'Группа Черкизово' ,'GCHE', 'GCHE.ME'),
(1304, 'BankUnited, Inc.' ,'BKU', 'BKU'),
(1305, 'GCP Applied Technologies Inc' ,'GCP', 'GCP'),
(1306, 'Vonovia SE' ,'VNA@DE', 'VNA.DE'),
(1307, 'Bionano Genomics, Inc.' ,'BNGO', 'BNGO'),
(1308, 'Heska Corp' ,'HSKA', 'HSKA'),
(1309, 'Halozyme Therapeutics Inc' ,'HALO', 'HALO'),
(1310, 'Johnson & Johnson' ,'JNJ', 'JNJ'),
(1311, 'Русская аквакультура' ,'AQUA', 'AQUA.ME'),
(1312, 'Белон' ,'BLNG', 'BLNG.ME'),
(1313, 'Мосэнерго' ,'MSNG', 'MSNG.ME'),
(1314, 'Albany International Corp.' ,'AIN', 'AIN'),
(1315, 'CONMED Corporation' ,'CNMD', 'CNMD'),
(1316, 'Sinopec Shanghai Petrochemical' ,'SHI', 'SHI'),
(1317, 'Applied Industrial Technologies' ,'AIT', 'AIT'),
(1318, 'City Holding Company' ,'CHCO', 'CHCO'),
(1319, 'Татнефть - привилегированные акции' ,'TATNP', 'TATNP.ME'),
(1320, 'Kroger' ,'KR', 'KR'),
(1321, 'MarketAxess Holdings Inc' ,'MKTX', 'MKTX'),
(1322, 'Prologis REIT' ,'PLD', 'PLD'),
(1323, 'Vimeo' ,'VMEO', 'VMEO'),
(1324, 'Сургутнефтегаз' ,'SNGS', 'SNGS.ME'),
(1325, 'Robinhood Markets, Inc.' ,'HOOD', 'HOOD'),
(1326, 'Martin Marietta Materials' ,'MLM', 'MLM'),
(1327, 'TJX' ,'TJX', 'TJX'),
(1328, 'Gentherm Inc' ,'THRM', 'THRM'),
(1329, 'Dow Inc' ,'DOW', 'DOW'),
(1330, 'Monster Beverage' ,'MNST', 'MNST'),
(1331, 'Anheuser-Busch InBev' ,'BUD', 'BUD'),
(1332, 'Bandwidth Inc' ,'BAND', 'BAND'),
(1333, 'NXP Semiconductors NV' ,'NXPI', 'NXPI'),
(1334, 'Exact Sciences Corp' ,'EXAS', 'EXAS'),
(1335, 'Entergy Corporation' ,'ETR', 'ETR'),
(1336, 'JELD-WEN Holding Inc' ,'JELD', 'JELD'),
(1337, 'Zimmer Biomet Holdings' ,'ZBH', 'ZBH'),
(1338, 'ContextLogic' ,'WISH', 'US21077C1071.SG'),
(1339, 'Comcast' ,'CMCSA', 'CMCSA'),
(1340, 'Alnylam Pharmaceuticals Inc' ,'ALNY', 'ALNY'),
(1341, 'Tactile Systems Technology Inc' ,'TCMD', 'TCMD'),
(1342, 'CSX Corp' ,'CSX', 'CSX'),
(1343, 'Carnival' ,'CCL', 'CCL'),
(1344, 'nLight Inc' ,'LASR', 'LASR'),
(1345, 'PRA Health Sciences Inc' ,'PRAH', '-'),
(1346, 'Slack Technologies Inc' ,'WORK', '-'),
(1347, 'Taylor Morrison Home Corp' ,'TMHC', 'TMHC'),
(1348, 'Edgewell Personal Care Co' ,'EPC', 'EPC'),
(1349, 'ТГК-1' ,'TGKA', 'TGKA.ME'),
(1350, 'Nexters Inc' ,'GDEV', 'GDEV'),
(1351, 'American Woodmark Corp' ,'AMWD', 'AMWD'),
(1352, 'Upwork Inc' ,'UPWK', 'UPWK'),
(1353, 'Adobe' ,'ADBE', 'ADBE'),
(1354, 'National Instruments' ,'NATI', 'NATI'),
(1355, 'Dr. Reddy''s Laboratories' ,'RDY', 'RDY'),
(1356, 'Toast' ,'TOST', 'TOST'),
(1357, 'Travel + Leisure Co.' ,'TNL', 'TNL'),
(1358, 'Kimberly-Clark' ,'KMB', 'KMB'),
(1359, 'Allianz SE' ,'ALV@DE', 'ALV.DE'),
(1360, 'EastGroup Properties REIT' ,'EGP', 'EGP'),
(1361, 'Juniper Networks' ,'JNPR', 'JNPR'),
(1362, 'GreenSky Inc' ,'GSKY', 'GSKY'),
(1363, 'US Foods Holding Corp' ,'USFD', 'USFD'),
(1364, 'Switch Inc' ,'SWCH', 'SWCH'),
(1365, 'Progress Software Corp' ,'PRGS', 'PRGS'),
(1366, 'VK' ,'VKCO', 'VKCO.IL'),
(1367, 'Atara Biotherapeutics Inc' ,'ATRA', 'ATRA'),
(1368, 'NewMarket Corp' ,'NEU', 'NEU'),
(1369, 'STORE Capital Corp REIT' ,'STOR', 'STOR'),
(1370, 'Casella Waste Systems' ,'CWST', 'CWST'),
(1371, 'Cassava Sciences' ,'SAVA', 'SAVA'),
(1372, 'United Rentals' ,'URI', 'URI'),
(1373, 'Globe Life Inc' ,'GL', 'GL'),
(1374, 'Teledyne Technologies Inc' ,'TDY', 'TDY'),
(1375, 'РуссНефть' ,'RNFT', 'RNFT.ME'),
(1376, 'Haemonetics Corp' ,'HAE', 'HAE'),
(1377, 'Public Storage REIT' ,'PSA', 'PSA'),
(1378, 'Zynex Inc' ,'ZYXI', 'ZYXI'),
(1379, 'Cracker Barrel Old Country Sto' ,'CBRL', 'CBRL'),
(1380, 'Axogen Inc' ,'AXGN', 'AXGN'),
(1381, 'Micron Technology' ,'MU', 'MU'),
(1382, 'Акрон' ,'AKRN', 'AKRN.ME'),
(1383, 'Healthpeak Properties REIT' ,'PEAK', 'PEAK'),
(1384, 'Poshmark' ,'POSH', 'POSH'),
(1385, 'Donaldson Co' ,'DCI', 'DCI'),
(1386, 'PC Connection Inc' ,'CNXN', 'CNXN'),
(1387, 'Moelis & Co' ,'MC', 'MC'),
(1388, 'Under Armour (C)' ,'UA', 'UA'),
(1389, 'РусАгро' ,'AGRO', 'AGRO.IL'),
(1390, 'CenturyLink' ,'LUMNold', '-'),
(1391, 'GitLab' ,'GTLB', 'GTLB'),
(1392, 'Toll Brothers Inc' ,'TOL', 'TOL'),
(1393, 'Paychex Inc' ,'PAYX', 'PAYX'),
(1394, 'NOW Inc' ,'DNOW', 'DNOW'),
(1395, 'Cytokinetics' ,'CYTK', 'CYTK'),
(1396, 'Activision Blizzard' ,'ATVI', 'ATVI'),
(1397, 'STAG Industrial REIT' ,'STAG', 'STAG'),
(1398, 'Diodes Inc' ,'DIOD', 'DIOD'),
(1399, 'Alleghany Corp' ,'Y', 'Y'),
(1400, 'Corsair Gaming Inc' ,'CRSR', 'CRSR'),
(1401, 'Vocera Communications Inc' ,'VCRA', 'VCRA'),
(1402, 'Beam Therapeutics' ,'BEAM', 'BEAM'),
(1403, 'Nicolet Bankshares' ,'NCBS', 'NCBS'),
(1404, 'Corteva Inc' ,'CTVA', 'CTVA'),
(1405, 'Duke Realty REIT' ,'DRE', 'DRE'),
(1406, 'Airbnb, Inc' ,'ABNB', 'ABNB'),
(1407, 'Stride, Inc' ,'LRN', 'LRN'),
(1408, 'Oshkosh Corporation' ,'OSK', 'OSK'),
(1409, 'Halliburton' ,'HAL', 'HAL'),
(1410, 'Yelp Inc' ,'YELP', 'YELP'),
(1411, 'Technip Energies N.V.' ,'TE', 'TE.PA'),
(1412, 'Lam Research' ,'LRCX', 'LRCX'),
(1413, 'Tennant Company' ,'TNC', 'TNC'),
(1414, 'ESCO Technologies Inc.' ,'ESE', 'ESE'),
(1415, 'Bright Horizons Family Solutio' ,'BFAM', 'BFAM'),
(1416, 'Align Technology' ,'ALGN', 'ALGN'),
(1417, 'BOEING' ,'BA', 'BA'),
(1418, 'Fate Therapeutics Inc' ,'FATE', 'FATE'),
(1419, 'Berkeley Lights' ,'BLI', 'BLI'),
(1420, 'Stellantis N.V.' ,'STLA', 'STLA.MI'),
(1421, 'Финансовая группа БУДУЩЕЕ' ,'FTRE', '-'),
(1422, 'Pacific Biosciences of California' ,'PACB', 'PACB'),
(1423, 'AT&T' ,'T', 'T'),
(1424, 'HUGO BOSS AG' ,'BOSS@DE', 'BOSS.DE'),
(1425, 'КАМАЗ' ,'KMAZ', 'KMAZ.ME'),
(1426, 'Victorias Secret & Co.' ,'VSCO', 'VSCO'),
(1427, 'RWE AG' ,'RWE@DE', 'RWE.DE'),
(1428, 'StoneCo' ,'STNE', 'STNE'),
(1429, 'Exelixis Inc' ,'EXEL', 'EXEL'),
(1430, 'Regeneron Pharmaceuticals' ,'REGN', 'REGN'),
(1431, 'Amedisys Inc' ,'AMED', 'AMED'),
(1432, 'Belden Inc' ,'BDC', 'BDC'),
(1433, 'Novolipetsk Steel PJSC' ,'NLMK@GS', 'NLMK.IL'),
(1434, 'KB Home' ,'KBH', 'KBH'),
(1435, 'Ligand Pharmaceuticals Inc' ,'LGND', 'LGND'),
(1436, 'Constellation Energy' ,'CEG', 'CEG'),
(1437, 'Westlake Chemical' ,'WLK', 'WLK'),
(1438, 'АДР Циан' ,'CIAN', 'CIAN'),
(1439, 'Raytheon Technologies' ,'RTX', 'RTX'),
(1440, 'Biglari Holdings Inc' ,'BH', 'BH'),
(1441, 'Вторая генерирующая компания оптового рынка электроэнергии' ,'OGKB', 'OGKB.ME'),
(1442, 'Churchill Downs Inc' ,'CHDN', 'CHDN'),
(1443, 'Tattooed Chef, Inc.' ,'TTCF', 'TTCF'),
(1444, 'DuPont de Nemours Inc' ,'DD', 'DD'),
(1445, 'STAAR Surgical Co' ,'STAA', 'STAA'),
(1446, 'Stepan Company' ,'SCL', 'SCL'),
(1447, 'Arrival' ,'ARVL', 'ARVL'),
(1448, 'FleetCor Technologies Inc' ,'FLT', 'FLT'),
(1449, 'American States Water Co' ,'AWR', 'AWR'),
(1450, 'Axos Financial Inc' ,'AX', 'AX'),
(1451, 'Alcon' ,'ALC', 'ALC.SW'),
(1452, 'Российские сети' ,'RSTI', 'RSTI.ME'),
(1453, 'Veritiv Corp' ,'VRTV', 'VRTV'),
(1454, 'Howmet Aerospace' ,'HWM', 'HWM'),
(1455, 'Olin Corp' ,'OLN', 'OLN'),
(1456, 'Guangshen Railway' ,'GSH', '-'),
(1457, 'Chevron' ,'CVX', 'CVX'),
(1458, 'РУСАЛ' ,'RUAL_old', '0486.HK'),
(1459, 'CorVel Corp' ,'CRVL', 'CRVL'),
(1460, 'Shenandoah Telecommunications' ,'SHEN', 'SHEN'),
(1461, 'Aerie Pharmaceuticals Inc' ,'AERI', 'AERI'),
(1462, 'Twenty-First Century Fox' ,'FOX', 'FOX'),
(1463, 'Commerce Bancshares' ,'CBSH', 'CBSH'),
(1464, 'PG&E' ,'PCG', 'PCG'),
(1465, 'Alteryx Inc' ,'AYX', 'AYX'),
(1466, 'Penumbra Inc' ,'PEN', 'PEN'),
(1467, 'Alight' ,'ALIT', 'ALIT'),
(1468, 'Global Payments' ,'GPN', 'GPN'),
(1469, 'Huntington Bancshares' ,'HBAN', 'HBAN'),
(1470, 'Landstar System' ,'LSTR', 'LSTR'),
(1471, 'Autoliv, Inc.' ,'ALV', 'ALV'),
(1472, 'Bio-Rad Laboratories Inc' ,'BIO', 'BIO'),
(1473, 'Visa' ,'V', 'V'),
(1474, 'NVIDIA' ,'NVDA', 'NVDA'),
(1475, 'Xencor Inc' ,'XNCR', 'XNCR'),
(1476, 'California Water Service' ,'CWT', 'CWT'),
(1477, 'Татнефть' ,'TATN', 'TATN.ME'),
(1478, 'Continental Resources Inc' ,'CLR', 'CLR'),
(1479, 'Томская распределительная компания' ,'TORS', 'TORS.ME'),
(1480, 'Quaker Chemical Corp' ,'KWR', 'KWR'),
(1481, 'Western Union' ,'WU', 'WU'),
(1482, 'Arcutis Biotherapeutics' ,'ARQT', 'ARQT'),
(1483, 'Magnit PJSC' ,'MGNT@GS', 'MGNT.IL'),
(1484, 'Kopin Corporation' ,'KOPN', 'KOPN'),
(1485, 'QIAGEN NV' ,'QGEN', 'QGEN'),
(1486, 'Science Applications Internati' ,'SAIC', 'SAIC'),
(1487, 'Elanco Animal Health Inc' ,'ELAN', 'ELAN'),
(1488, 'Zynerba Pharmaceuticals Inc' ,'ZYNE', 'ZYNE'),
(1489, 'Advanced Energy Industries Inc' ,'AEIS', 'AEIS'),
(1490, 'American Outdoor Brands Inc' ,'AOUT', 'AOUT'),
(1491, 'Marathon Digital Holdings' ,'MARA', 'MARA'),
(1492, 'EOG Resources' ,'EOG', 'EOG'),
(1493, 'Old Dominion Freight Line Inc' ,'ODFL', 'ODFL'),
(1494, 'Madrigal Pharmaceuticals Inc' ,'MDGL', 'MDGL'),
(1495, 'Dun & Bradstreet Holdings' ,'DNB', 'DNB'),
(1496, 'PNC Financial Services' ,'PNC', 'PNC'),
(1497, 'Пермэнергосбыт - акции привилегированные' ,'PMSBP', 'PMSBP.ME'),
(1498, 'Heron Therapeutics Inc' ,'HRTX', 'HRTX'),
(1499, 'Dillard''s Inc' ,'DDS', 'DDS'),
(1500, 'Ростелеком' ,'RTKM', 'RTKM.ME'),
(1501, 'Entegris Inc' ,'ENTG', 'ENTG'),
(1502, 'H&R Block' ,'HRB', 'HRB'),
(1503, 'Cohen & Steers Inc' ,'CNS', 'CNS'),
(1504, 'Power Integrations Inc' ,'POWI', 'POWI'),
(1505, 'Cabot Microelectronics' ,'CCMP_old', 'CCMP'),
(1506, 'Matson Inc' ,'MATX', 'MATX'),
(1507, 'Overstock.com' ,'OSTK', 'OSTK'),
(1508, 'Synopsys' ,'SNPS', 'SNPS'),
(1509, 'British American Tobacco' ,'BTI', 'BTI'),
(1510, 'NIKE' ,'NKE', 'NKE'),
(1511, 'ВСМПО-АВИСМА' ,'VSMO', 'VSMO.ME'),
(1512, 'Southern Copper Corp' ,'SCCO', 'SCCO'),
(1513, 'Cars.com Inc' ,'CARS', 'CARS'),
(1514, 'McGrath RentCorp' ,'MGRC', 'MGRC'),
(1515, 'Zillow Group Inc' ,'ZG', 'ZG'),
(1516, 'Health Catalyst' ,'HCAT', 'HCAT'),
(1517, 'Union Pacific Corporation' ,'UNP', 'UNP'),
(1518, 'Keysight Technologies Inc' ,'KEYS', 'KEYS'),
(1519, 'CACI International' ,'CACI', 'CACI'),
(1520, 'AGNC Investment REIT' ,'AGNC', 'AGNC'),
(1521, 'Bio-Techne' ,'TECH', 'TECH'),
(1522, 'Genpact Limited' ,'G', 'G'),
(1523, 'Materion Corp' ,'MTRN', 'MTRN'),
(1524, 'Visteon Corp' ,'VC', 'VC'),
(1525, 'IPG' ,'IPG', 'IPG'),
(1526, 'Applied Molecular Transport' ,'AMTI', 'AMTI'),
(1527, 'Deluxe Corp' ,'DLX', 'DLX'),
(1528, 'Strategic Education Inc' ,'STRA', 'STRA'),
(1529, 'Dave & Buster''s Entertainment Inc' ,'PLAY', 'PLAY'),
(1530, 'Children''s Place Inc The' ,'PLCE', 'PLCE'),
(1531, 'М.видео' ,'MVID', 'MVID.ME'),
(1532, 'Marriott Vacations Worldwide Corporation' ,'VAC', 'VAC'),
(1533, 'TPI Composites Inc' ,'TPIC', 'TPIC'),
(1534, 'McCormick & Co' ,'MKC', 'MKC'),
(1535, 'Aspen Technology Inc' ,'AZPN', 'AZPN'),
(1536, 'Skillz Inc' ,'SKLZ', 'SKLZ'),
(1537, 'Hamilton Lane Incorporated' ,'HLNE', 'HLNE'),
(1538, 'Murphy Oil' ,'MUR', 'MUR'),
(1539, 'Stoneridge Inc' ,'SRI', 'SRI'),
(1540, 'Eaton Corporation' ,'ETN', 'ETN'),
(1541, 'Linde' ,'LIN', 'LIN'),
(1542, 'Broadridge Financial Solutions' ,'BR', 'BR'),
(1543, 'EPAM Systems' ,'EPAM', 'EPAM'),
(1544, 'Gartner' ,'IT', 'IT'),
(1545, 'Mohawk Industries' ,'MHK', 'MHK'),
(1546, 'PulteGroup' ,'PHM', 'PHM'),
(1547, 'Archer-Daniels-Midland Company' ,'ADM', 'ADM'),
(1548, 'Lucid Group' ,'LCID', 'LCID'),
(1549, 'Nordstrom' ,'JWN', 'JWN'),
(1550, 'Salesforce' ,'CRM', 'CRM'),
(1551, 'Ulta Beauty' ,'ULTA', 'ULTA'),
(1552, 'Target' ,'TGT', 'TGT'),
(1553, 'People''s United Financial' ,'PBCT', 'PBCT'),
(1554, 'Luminar Technologies' ,'LAZR', 'LAZR'),
(1555, 'OraSure Technologies Inc' ,'OSUR', 'OSUR'),
(1556, 'Pennant Group Inc' ,'PNTG', 'PNTG'),
(1557, 'Carl Zeiss Meditec AG' ,'AFX@DE', 'AFX.DE'),
(1558, 'Funko Inc' ,'FNKO', 'FNKO'),
(1559, 'Magna International Inc.' ,'MGA', 'MG.TO'),
(1560, 'Floor & Decor Holdings Inc' ,'FND', 'FND'),
(1561, 'International Paper' ,'IP', 'IP'),
(1562, 'Huazhu Group' ,'HTHT', 'HTHT'),
(1563, 'Valero Energy Corporation' ,'VLO', 'VLO'),
(1564, 'Bristol-Myers Squibb' ,'BMY', 'BMY'),
(1565, 'Carvana Co' ,'CVNA', 'CVNA'),
(1566, 'Kadant Inc.' ,'KAI', 'KAI'),
(1567, 'Littelfuse' ,'LFUS', 'LFUS'),
(1568, 'Русолово' ,'ROLO', 'ROLO.ME'),
(1569, 'Palo Alto Networks' ,'PANW', 'PANW'),
(1570, 'Ambarella' ,'AMBA', 'AMBA'),
(1571, 'Middleby Corp The' ,'MIDD', 'MIDD'),
(1572, 'ПИК' ,'PIKK', 'PIKK.ME'),
(1573, 'Vipshop' ,'VIPS', 'VIPS'),
(1574, 'CorEnergy Infrastructure REIT' ,'CORR', 'CORR'),
(1575, 'Blackstone' ,'BX', 'BX'),
(1576, 'НЛМК' ,'NLMK', 'NLMK.ME'),
(1577, 'CenterPoint Energy' ,'CNP', 'CNP'),
(1578, 'CyberArk Software Ltd' ,'CYBR', 'CYBR'),
(1579, 'Campbell Soup' ,'CPB', 'CPB'),
(1580, 'Camden Property REIT' ,'CPT', 'CPT'),
(1581, 'Apartment Income REIT' ,'AIRC', 'AIRC'),
(1582, 'World Acceptance Corp' ,'WRLD', 'WRLD'),
(1583, 'Stitch Fix' ,'SFIX', 'SFIX'),
(1584, 'Graham Holdings Co' ,'GHC', 'GHC'),
(1585, 'Akamai Technologies' ,'AKAM', 'AKAM'),
(1586, 'Oceaneering International Inc' ,'OII', 'OII'),
(1587, 'Denali Therapeutics Inc' ,'DNLI', 'DNLI'),
(1588, 'Bill.com Holdings Inc' ,'BILL', 'BILL'),
(1589, 'Twitter' ,'TWTR', 'TWTR'),
(1590, 'Angi Inc' ,'ANGI', 'ANGI'),
(1591, 'Teradata' ,'TDC', 'TDC'),
(1592, 'Abiomed Inc' ,'ABMD', 'ABMD'),
(1593, 'Avista Corporation' ,'AVA', 'AVA'),
(1594, 'Bayer' ,'BAYN@DE', 'BAYN.DE'),
(1595, 'Northrop Grumman' ,'NOC', 'NOC'),
(1596, 'ТГК-14' ,'TGKN', 'TGKN.ME'),
(1597, 'Globant SA' ,'GLOB', 'GLOB'),
(1598, 'Air Products & Chemicals' ,'APD', 'APD'),
(1599, 'Orthofix Medical Inc' ,'OFIX', 'OFIX'),
(1600, 'Bank of New York Mellon' ,'BK', 'BK'),
(1601, 'Dynatrace Inc' ,'DT', 'DT'),
(1602, 'ExlService Holdings Inc' ,'EXLS', 'EXLS'),
(1603, 'UMB Financial' ,'UMBF', 'UMBF'),
(1604, 'Thor Industries Inc' ,'THO', 'THO'),
(1605, 'EverQuote' ,'EVER', 'EVER'),
(1606, 'Goodyear Tire & Rubber' ,'GT', 'GT'),
(1607, 'Kirby Corp' ,'KEX', 'KEX'),
(1608, 'Sturm Ruger & Co Inc' ,'RGR', 'RGR'),
(1609, 'Hanesbrands' ,'HBI', 'HBI'),
(1610, 'Транснефть - привилегированные акции' ,'TRNFP', 'TRNFP.ME'),
(1611, 'AZEK Company' ,'AZEK', 'AZEK'),
(1612, 'Inseego Corp' ,'INSG', 'INSG'),
(1613, 'Cognyte Software Ltd.' ,'CGNT', 'CGNT'),
(1614, 'Zscaler Inc' ,'ZS', 'ZS'),
(1615, 'Analog Devices' ,'ADI', 'ADI'),
(1616, 'VMware' ,'VMW', 'VMW'),
(1617, 'Integer Holdings Corp' ,'ITGR', 'ITGR'),
(1618, 'Biogen' ,'BIIB', 'BIIB'),
(1619, 'Workiva Inc' ,'WK', 'WK'),
(1620, 'Essex Property REIT' ,'ESS', 'ESS'),
(1621, 'Tandem Diabetes Care Inc' ,'TNDM', 'TNDM'),
(1622, 'Quest Diagnostics' ,'DGX', 'DGX'),
(1623, 'Danaher' ,'DHR', 'DHR'),
(1624, 'Spectrum Brands Holdings Inc' ,'SPB@US', 'SPB'),
(1625, 'Colfax Corp' ,'CFX', 'CFX'),
(1626, 'Autodesk' ,'ADSK', 'ADSK'),
(1627, 'Medpace Holdings Inc' ,'MEDP', 'MEDP'),
(1628, 'Southern' ,'SO', 'SO'),
(1629, 'REGENXBIO Inc' ,'RGNX', 'RGNX'),
(1630, 'WW Grainger' ,'GWW', 'GWW'),
(1631, 'МТС' ,'MTSS', 'MTSS.ME'),
(1632, 'SPS Commerce Inc' ,'SPSC', 'SPSC'),
(1633, 'Красный Октябрь' ,'KROT', 'KROT.ME'),
(1634, 'Patrick Industries Inc' ,'PATK', 'PATK'),
(1635, 'Dominion Energy Inc' ,'D', 'D'),
(1636, 'Xerox' ,'XRX', 'XRX'),
(1637, 'Группа ЛСР' ,'LSRG', 'LSRG.ME'),
(1638, 'Sage Therapeutics Inc' ,'SAGE', 'SAGE'),
(1639, 'BOK Financial' ,'BOKF', 'BOKF'),
(1640, 'USANA Health Sciences Inc' ,'USNA', 'USNA'),
(1641, 'IAC InterActiveCorp' ,'IAC_old', 'IAC'),
(1642, 'Artivion' ,'AORT', 'AORT'),
(1643, 'Mirati Therapeutics Inc' ,'MRTX', 'MRTX'),
(1644, 'ЯТЭК' ,'YAKG', 'YAKG.ME'),
(1645, 'Rhythm Pharmaceuticals Inc' ,'RYTM', 'RYTM'),
(1646, 'United Technologies' ,'UTX', '-'),
(1647, 'Sysco' ,'SYY', 'SYY'),
(1648, 'Fidelity National Information' ,'FIS', 'FIS'),
(1649, 'Armstrong World Industries Inc' ,'AWI', 'AWI'),
(1650, 'Freedom Holding Corp/NV' ,'FRHC', 'FRHC'),
(1651, 'Сургутнефтегаз - привилегированные акции' ,'SNGSP', 'SNGSP.ME'),
(1652, 'Under Armour' ,'UAA', 'UAA'),
(1653, 'Clearway Energy' ,'CWEN', 'CWEN'),
(1654, 'Cincinnati Financial Corporation' ,'CINF', 'CINF'),
(1655, 'НМТП' ,'NMTP', 'NMTP.ME'),
(1656, 'Chesapeake Energy Corporation' ,'CHK', '-'),
(1657, 'Compass Minerals International' ,'CMP', 'CMP'),
(1658, 'Varex Imaging Corp' ,'VREX', 'VREX'),
(1659, 'Huntington Ingalls Industries Inc' ,'HII', 'HII'),
(1660, 'Sohu.com' ,'SOHU', 'SOHU'),
(1661, 'FTC Solar, Inc.' ,'FTCI', 'FTCI'),
(1662, 'ONE Gas' ,'OGS', 'OGS'),
(1663, 'Nutanix Inc' ,'NTNX', 'NTNX'),
(1664, 'Moderna Inc' ,'MRNA', 'MRNA'),
(1665, 'RingCentral Inc' ,'RNG', 'RNG'),
(1666, 'Магнитогорский металлургический комбинат' ,'MAGN', 'MAGN.ME'),
(1667, 'XPO Logistics Inc' ,'XPO', 'XPO'),
(1668, 'Ленэнерго - акции привилегированные' ,'LSNGP', 'LSNGP.ME'),
(1669, 'AbCellera Biologics' ,'ABCL', 'ABCL'),
(1670, 'Mattel' ,'MAT', 'MAT'),
(1671, 'Muenchener Rueckversicherungs-Gesellschaft AG' ,'MUV2@DE', 'MUV2.DE'),
(1672, 'BeyondSpring' ,'BYSI', 'BYSI'),
(1673, 'Dell Technologies Inc' ,'DELL', 'DELL'),
(1674, 'Textron' ,'TXT', 'TXT'),
(1675, 'Лензолото - привилегированные акции' ,'LNZLP', 'LNZLP.ME'),
(1676, 'СПБ Биржа' ,'SPBE', 'SPBE.ME'),
(1677, 'Cal-Maine Foods Inc' ,'CALM', 'CALM'),
(1678, 'Cleanspark Inc' ,'CLSK', 'CLSK'),
(1679, 'EchoStar Corporation' ,'SATS', 'SATS'),
(1680, 'Recursion Pharmaceuticals, Inc.' ,'RXRX', 'RXRX'),
(1681, 'Pegasystems Inc' ,'PEGA', 'PEGA'),
(1682, 'Hain Celestial Group Inc' ,'HAIN', 'HAIN'),
(1683, 'Avanos Medical Inc' ,'AVNS', 'AVNS'),
(1684, 'Copart Inc' ,'CPRT', 'CPRT'),
(1685, 'Газпром нефть' ,'SIBN', 'SIBN.ME'),
(1686, 'Нижнекамскнефтехим - акции привилегированные' ,'NKNCP', 'NKNCP.ME'),
(1687, 'Broadcom' ,'AVGO', 'AVGO'),
(1688, 'Evonik Industries AG' ,'EVK@DE', 'EVK.DE'),
(1689, 'ALX Oncology Holdings Inc' ,'ALXO', 'ALXO'),
(1690, 'ДЭК' ,'DVEC', 'DVEC.ME'),
(1691, 'Natera inc' ,'NTRA', 'NTRA'),
(1692, 'Наука-Связь' ,'NSVZ', 'NSVZ.ME'),
(1693, 'Skyworks Solutions' ,'SWKS', 'SWKS'),
(1694, 'Tri Pointe Homes, Inc.' ,'TPH', 'TPH'),
(1695, 'AGCO Corp' ,'AGCO', 'AGCO'),
(1696, 'Ренессанс Страхование' ,'RENI', 'RENI.ME'),
(1697, 'Crowdstrike Holdings Inc' ,'CRWD', 'CRWD'),
(1698, 'ТГК-2 - акции привилегированные' ,'TGKBP', 'TGKBP.ME'),
(1699, '1-800-Flowers.com Inc' ,'FLWS', 'FLWS'),
(1700, 'Upstart Holdings' ,'UPST', 'US91680M1071.SG'),
(1701, 'Abercrombie & Fitch' ,'ANF', 'ANF'),
(1702, 'PhosAgro PJSC' ,'PHOR@GS', 'PHOR.IL'),
(1703, 'Astronics Corp' ,'ATRO', 'ATRO'),
(1704, 'TransUnion' ,'TRU', 'TRU'),
(1705, 'Huron Consulting Group Inc' ,'HURN', 'HURN'),
(1706, 'Newmont Goldcorp Corporation' ,'NEM', 'NEM'),
(1707, 'Celanese Corp' ,'CE', 'CE'),
(1708, 'Genesco Inc' ,'GCO', 'GCO'),
(1709, 'Frontier Communications' ,'FTR', '-'),
(1710, 'Adidas' ,'ADS@DE', 'ADS.DE'),
(1711, 'Lamb Weston Holdings Inc' ,'LW', 'LW'),
(1712, 'TotalEnergies SE' ,'TTE', 'TOTA.SG'),
(1713, 'Tenable Holdings Inc' ,'TENB', 'TENB'),
(1714, 'Stericycle' ,'SRCL', 'SRCL'),
(1715, 'LivePerson Inc' ,'LPSN', 'LPSN'),
(1716, 'Flowers Foods, Inc.' ,'FLO', 'FLO'),
(1717, 'Emerson Electric' ,'EMR', 'EMR'),
(1718, 'General Motors' ,'GM', 'GM'),
(1719, 'Chipotle Mexican Grill' ,'CMG', 'CMG'),
(1720, 'OrthoPediatrics Corp' ,'KIDS', 'KIDS'),
(1721, 'Inter Parfums Inc' ,'IPAR', 'IPAR'),
(1722, 'Merck KGaA' ,'MRK@DE', 'MRK.DE'),
(1723, 'Black Diamond Therapeutics Inc' ,'BDTX', 'BDTX'),
(1724, 'State Street' ,'STT', 'STT'),
(1725, 'Atea Pharmaceuticals' ,'AVIR', 'AVIR'),
(1726, 'Prothena Corporation' ,'PRTA', 'PRTA'),
(1727, 'Bath & Body Works' ,'BBWI', 'BBWI'),
(1728, 'Zumiez Inc' ,'ZUMZ', 'ZUMZ'),
(1729, 'Fidelity National Financial, Inc.' ,'FNF', 'FNF'),
(1730, 'НОВАТЭК' ,'NVTK', 'NVTK.ME'),
(1731, 'Installed Building Products' ,'IBP', 'IBP'),
(1732, '3M Company' ,'MMM', 'MMM'),
(1733, 'FRP Holdings Inc' ,'FRPH', 'FRPH'),
(1734, 'Surmodics Inc' ,'SRDX', 'SRDX'),
(1735, 'Квадра' ,'TGKD', 'TGKD.ME'),
(1736, 'Quanta Services' ,'PWR', 'PWR'),
(1737, 'Equinix REIT' ,'EQIX', 'EQIX'),
(1738, 'Royal Gold' ,'RGLD', 'RGLD'),
(1739, 'ChoiceOne Financial Services, Inc.' ,'COFS', 'COFS'),
(1740, 'VeriSign' ,'VRSN', 'VRSN'),
(1741, 'Eargo' ,'EAR', 'EAR'),
(1742, 'Мечел' ,'MTLR', 'MTLR.ME'),
(1743, 'NRG Energy' ,'NRG', 'NRG'),
(1744, 'Datadog Inc' ,'DDOG', 'DDOG'),
(1745, 'Curtiss-Wright' ,'CW', 'CW'),
(1746, 'Forrester Research Inc' ,'FORR', 'FORR'),
(1747, 'NortonLifeLock Inc' ,'NLOK', 'NLOK'),
(1748, '2seventy bio' ,'TSVT', 'TSVT'),
(1749, 'Axcelis Technologies' ,'ACLS', 'ACLS'),
(1750, 'AutoNation' ,'AN', 'AN'),
(1751, 'РКК Энергия им.С.П.Королева' ,'RKKE', 'RKKE.ME'),
(1752, 'Itron Inc' ,'ITRI', 'ITRI'),
(1753, '2U Inc' ,'TWOU', 'TWOU'),
(1754, 'ГДР Лента' ,'LNTA', 'LNTA.IL'),
(1755, 'First Solar' ,'FSLR', 'FSLR'),
(1756, 'MKS Instruments' ,'MKSI', 'MKSI'),
(1757, 'Catalent Inc' ,'CTLT', 'CTLT'),
(1758, 'ACM Research Inc' ,'ACMR', 'ACMR'),
(1759, 'Citigroup' ,'C', 'C'),
(1760, 'Vicor Corp' ,'VICR', 'VICR'),
(1761, 'Allscripts Healthcare Solution' ,'MDRX', 'MDRX'),
(1762, 'UiPath, Inc.' ,'PATH', 'PATH'),
(1763, 'Skyline Champion' ,'SKY', 'SKY'),
(1764, 'Best Buy Co.' ,'BBY', 'BBY'),
(1765, 'Apartment Investment & Management REIT' ,'AIV', 'AIV'),
(1766, 'CMC Materials' ,'CCMP', 'CCMP'),
(1767, 'Vail Resorts Inc' ,'MTN', 'MTN'),
(1768, 'Perficient Inc' ,'PRFT', 'PRFT'),
(1769, 'Deutsche Wohnen SE' ,'DWNI@DE', 'DWNI.DE'),
(1770, 'Spirit Airlines Inc' ,'SAVE', 'SAVE'),
(1771, 'Illinois Tool Works' ,'ITW', 'ITW'),
(1772, 'Toro' ,'TTC', 'TTC'),
(1773, 'Expeditors' ,'EXPD', 'EXPD'),
(1774, 'Abbott' ,'ABT', 'ABT'),
(1775, 'МРСК Сибири' ,'MRKS', 'MRKS.ME'),
(1776, 'Simulations Plus Inc.' ,'SLP', 'SLP'),
(1777, 'Farfetch Ltd' ,'FTCH', 'FTCH'),
(1778, 'Trane Technologies' ,'TT', 'TT'),
(1779, 'ChargePoint Holdings' ,'CHPT', 'CHPT'),
(1780, 'Match Group Inc' ,'MTCH_old', 'MTCH'),
(1781, 'China Life Insurance' ,'LFC', 'LFC'),
(1782, 'Simply Good Foods Co' ,'SMPL', 'SMPL'),
(1783, 'Iron Mountain REIT' ,'IRM', 'IRM'),
(1784, 'ZipRecruiter Inc' ,'ZIP', 'ZIP'),
(1785, 'Обувь России' ,'ORUP', 'ORUP.ME'),
(1786, 'Hershey' ,'HSY', 'HSY'),
(1787, 'NCR Corp' ,'NCR', 'NCR'),
(1788, 'Intuitive Surgical' ,'ISRG', 'ISRG'),
(1789, 'Mimecast Limited' ,'MIME', 'MIME'),
(1790, 'Premier Inc' ,'PINC', 'PINC'),
(1791, 'DexCom Inc' ,'DXCM', 'DXCM'),
(1792, 'ITT' ,'ITT', 'ITT'),
(1793, 'Granite Construction Inc' ,'GVA', 'GVA'),
(1794, 'SolarWinds Corp' ,'SWI', 'SWI'),
(1795, 'Clean Harbors Inc' ,'CLH', 'CLH'),
(1796, 'VIZIO Holding Corp.' ,'VZIO', 'VZIO'),
(1797, 'MSG Networks Inc' ,'MSGN', '-'),
(1798, 'Live Nation Entertainment Inc' ,'LYV', 'LYV'),
(1799, 'Paymentus Holdings' ,'PAY', 'PAY'),
(1800, 'New Fortress Energy' ,'NFE', 'NFE'),
(1801, 'Walgreens Boots Alliance' ,'WBA', 'WBA'),
(1802, 'Universal Display Corp' ,'OLED', 'OLED'),
(1803, 'Marqeta, Inc.' ,'MQ', 'MQ'),
(1804, 'National Vision Holdings Inc' ,'EYE', 'EYE'),
(1805, 'Lindsay Corporation' ,'LNN', 'LNN'),
(1806, 'Coupang, Inc.' ,'CPNG', 'CPNG'),
(1807, 'MRC Global Inc' ,'MRC', 'MRC'),
(1808, 'Ollie''s Bargain Outlet Holding' ,'OLLI', 'OLLI'),
(1809, 'Discovery Communications (A)' ,'DISCA', 'DISCA'),
(1810, 'MDU Resources Group, Inc.' ,'MDU', 'MDU'),
(1811, 'BWX Technologies' ,'BWXT', 'BWXT'),
(1812, 'Thermo Fisher Scientific' ,'TMO', 'TMO'),
(1813, 'Standex International Corp' ,'SXI', 'SXI'),
(1814, 'Exponent, Inc.' ,'EXPO', 'EXPO'),
(1815, 'SailPoint Technologies Holdings' ,'SAIL', 'SAIL'),
(1816, 'Century Communities' ,'CCS', 'CCS'),
(1817, 'Carpenter Technology Corp' ,'CRS', 'CRS'),
(1818, 'Evergy, Inc' ,'EVRG', 'EVRG'),
(1819, 'Пермэнергосбыт' ,'PMSB', 'PMSB.ME'),
(1820, 'RPM International Inc' ,'RPM', 'RPM'),
(1821, 'Chesapeake Energy Corporation' ,'CHKold', 'CHK'),
(1822, 'Chatham Lodging REIT' ,'CLDT', 'CLDT'),
(1823, 'Accenture' ,'ACN', 'ACN'),
(1824, 'PepsiCo' ,'PEP', 'PEP'),
(1825, 'ДВМП' ,'FESH', 'FESH.ME'),
(1826, 'Costco Wholesale' ,'COST', 'COST'),
(1827, 'Polymetal' ,'POLY', 'POLY.L'),
(1828, 'AMERISAFE, Inc.' ,'AMSF', 'AMSF'),
(1829, 'МКБ' ,'CBOM', 'CBOM.ME'),
(1830, 'Redfin Corp' ,'RDFN', 'RDFN'),
(1831, 'SP Plus Corp' ,'SP', 'SP'),
(1832, 'Genuine Parts' ,'GPC', 'GPC'),
(1833, 'Jacobs Engineering' ,'J', 'J'),
(1834, '51job' ,'JOBS', 'JOBS'),
(1835, 'Sberbank of Russia PJSC' ,'SBER@GS', 'SBRCY'),
(1836, 'Мостотрест' ,'MSTT', 'MSTT.ME'),
(1837, 'Asana' ,'ASAN', 'ASAN'),
(1838, 'Eli Lilly & Co' ,'LLY', 'LLY'),
(1839, 'Elastic NV' ,'ESTC', 'ESTC'),
(1840, 'MYR Group Inc' ,'MYRG', 'MYRG'),
(1841, 'Allakos Inc' ,'ALLK', 'ALLK'),
(1842, 'Дагестанская энергосбытовая компания' ,'DASB', '-'),
(1843, 'Sunrun Inc' ,'RUN', 'RUN'),
(1844, 'Korn Ferry' ,'KFY', 'KFY'),
(1845, 'ManTech International Corp VA' ,'MANT', 'MANT'),
(1846, 'Brunswick Corp DE' ,'BC', 'BC'),
(1847, 'Axalta Coating Systems' ,'AXTA', 'AXTA'),
(1848, 'Seattle Genetics Inc' ,'SGEN_old', 'SGEN'),
(1849, 'Balchem Corp' ,'BCPC', 'BCPC'),
(1850, 'Kimco Realty REIT' ,'KIM', 'KIM'),
(1851, 'InsperIty Inc' ,'NSP', 'NSP'),
(1852, 'Enphase Energy Inc' ,'ENPH', 'ENPH'),
(1853, 'iRhythm Technologies' ,'IRTC', 'IRTC'),
(1854, 'NetApp' ,'NTAP', 'NTAP'),
(1855, 'Cullen/Frost Bankers' ,'CFR', 'CFR'),
(1856, 'Peloton Interactive Inc' ,'PTON', 'PTON'),
(1857, 'Apollo Medical Holdings' ,'AMEH', 'AMEH'),
(1858, 'FormFactor Inc' ,'FORM', 'FORM'),
(1859, 'Primerica' ,'PRI', 'PRI'),
(1860, 'Columbia Sportswear Company' ,'COLM', 'COLM'),
(1861, 'WEC Energy Group' ,'WEC', 'WEC'),
(1862, 'Cooper Tire & Rubber Co' ,'CTB', '-'),
(1863, 'Arcturus Therapeutics Holdings' ,'ARCT', 'ARCT'),
(1864, 'Shopify Inc' ,'SHOP', 'SHOP'),
(1865, 'Gossamer Bio Inc' ,'GOSS', 'GOSS'),
(1866, 'Россети Центр' ,'MRKC', 'MRKC.ME'),
(1867, 'Livent Corporation' ,'LTHM', 'LTHM'),
(1868, 'Avon Products' ,'AVP', '-'),
(1869, 'TG Therapeutics' ,'TGTX', 'TGTX'),
(1870, 'Independent Bank Corp' ,'INDB', 'INDB'),
(1871, 'Humana' ,'HUM', 'HUM'),
(1872, 'Valvoline' ,'VVV', 'VVV'),
(1873, 'Cisco' ,'CSCO', 'CSCO'),
(1874, 'Warby Parker' ,'WRBY', 'WRBY'),
(1875, 'Интер РАО ЕЭС' ,'IRAO', 'IRAO.ME'),
(1876, 'Regency Centers REIT' ,'REG', 'REG'),
(1877, 'Nurix Therapeutics Inc' ,'NRIX', 'NRIX'),
(1878, 'Kellogg' ,'K', 'K'),
(1879, 'Verisk Analytics' ,'VRSK', 'VRSK'),
(1880, 'Perspecta' ,'PRSP', '-'),
(1881, 'Центральный Телеграф' ,'CNTL', 'CNTL.ME'),
(1882, 'КуйбышевАзот' ,'KAZT', 'KAZT.ME'),
(1883, 'Hess' ,'HES', 'HES'),
(1884, 'Yext Inc' ,'YEXT', 'YEXT'),
(1885, 'Hyliion Holdings Corp.' ,'HYLN', 'HYLN'),
(1886, 'CoreLogic Inc United States' ,'CLGX', '-'),
(1887, 'Endo International PLC' ,'ENDP', 'ENDP'),
(1888, 'Nokia' ,'NOK', 'NOK'),
(1889, 'Freeport-McMoRan' ,'FCX', 'FCX'),
(1890, 'Magnolia Oil & Gas Corp' ,'MGY', 'MGY'),
(1891, 'Аэрофлот' ,'AFLT', 'AFLT.ME'),
(1892, 'Schrodinger Inc' ,'SDGR', 'SDGR'),
(1893, 'Unum' ,'UNM', 'UNM'),
(1894, 'BASF SE' ,'BAS@DE', 'BAS.DE'),
(1895, 'ASGN Inc' ,'ASGN', 'ASGN'),
(1896, 'AerCap Holdings' ,'AER', 'AER'),
(1897, 'Lordstown Motors Corp' ,'RIDE', 'RIDE'),
(1898, 'АбрауДюрсо' ,'ABRD', 'ABRD.ME'),
(1899, 'CF Industries Holdings' ,'CF', 'CF'),
(1900, 'Constellation Pharmaceuticals' ,'CNST', '-'),
(1901, 'NV5 Global Inc' ,'NVEE', 'NVEE'),
(1902, 'American Homes 4 Rent REIT' ,'AMH', 'AMH')
